### ISSUE TITLE
River doesn't handle window size constraints nicely.

### ISSUE THREAD

**Issue by lazy-dolphin** [ifreund/river#10]
Decreasing the width of a master window with size constraints results in its overlap over stack windows.
![20200426_21h44m14s_grim](https://user-images.githubusercontent.com/51233180/80313908-b15e8180-880b-11ea-8f73-981e0c50fe81.png)

**Comment by ifreund** [comment]
hmm this seems to cause some issues on sway as well:
![image](https://user-images.githubusercontent.com/12723818/80314435-cfb78380-87f1-11ea-8755-aa575d026155.png)
We should probably handle this more gracefully, but I think other features will take priority for the time being.

**Comment by ifreund** [comment]
There isn't really a way to handle this better given how external layouts work. What we can do to improve this though is to implement  #59.
