### ISSUE TITLE
Find out a way to replicate sways "worksapce --no-auto-back-and-forth"

### ISSUE THREAD

**Issue by maringuu** [ifreund/river#101]
In sway when you switch workspaces (one workspace is eqivalent exactly one tag) you can switch to the same workspace twice. When you do the second switch it switches back to the previously focused workspace.

My use case that I often forget which tag I came from but know that I want to swich back. Also it makes me move my fingers less because I often look at workspaces really short meaning that I don't move my finger away to to keys to switch to the workspace I'm on.

My suggestion ist to add `set-focused-tagmask -back-and-forth` which has the same behaviour as the sway command  without specifying `--no-auto-back-and-forth` but for tagmasks instead of workspaces.
Could this be done any simpler, maybe without adding another option?

**Comment by ifreund** [comment]
What would be neat is if river was flexible and extensible enough for this to not require a builtin command. It's already possible with a script which stores state externally (e.g. as a file in `/tmp`) but that's a little more effort than I'd like this to require. I've been toying with the idea of taking yet more inspiration from kakoune and allowing the user to store/recall arbitrary values in the form of user defined options, however I'm not sure if that feature would be justified yet.

**Comment by maringuu** [comment]
Link to the kakoune docs for future reference.
https://github.com/mawww/kakoune/blob/master/doc/pages/options.asciidoc

**Comment by ifreund** [comment]
I'm closing this as I don't think the feature makes much sense for a tag-based and therefore don't want to implement in river itself.

Adding other more general features to make implementing this cleanly in river's "userland" would be reasonable, however such features deserve their own issue(s).
