### ISSUE TITLE
Provide layout generators with additional information to enable advanced dynamic layouts

### ISSUE THREAD

**Issue by Leon-Plickat** [ifreund/river#106]
Current idea as discussed in IRC:

River will send layout generators additional information about the currently visible views via stdin. Also the currently focused tag set is added to the command line arguments.

The information about each view will be: app_id! tag? title? requested size? CSD vs SSD status?

The information will be send in order of the views position in the view stack.

Existing layout generators will not be broken, since they will (if written correctly) just ignore the additional command argument and stdin.

**Comment by Leon-Plickat** [comment]
Alternative: Layout generators as compiled plugins -> `dlopen()`, shared objects

**Comment by ifreund** [comment]
>  Example: Layout gens could esiely hold private persistant data
> We should probably document that this should be stack, not heap.

static variables don't go on the stack but in the data segment. 

To quote from the `pam_set_data(3)` man page:
```
PAM modules may be dynamically loadable objects. In general such files
should not contain static variables. This function and its counterpart
pam_get_data(3), provide a mechanism for a module to associate some
data with the handle pamh.
```
So it would probably be good to figure out if/why that is the case. If so we could expose `river_set_data()` and `river_get_data()` functions to store/retrieve a pointer to heap-allocated resources.

**Comment by Leon-Plickat** [comment]
I am not exactly sure how those two functions would work. River will have no idea about what it allocates.

I propose:

* `void *river_get_data(size_t size)`  allocates `size` bytes and returns pointer to that, or if user data already exists return pointer to that and ignore `size`. Only a single user data object exists. River stores the pointer and frees it on exit.

* `river_free_data(void *ptr)` free user data pointer (Maybe a layout gen wants to change the size of its user data or simply does not need it anymore).

**Comment by Leon-Plickat** [comment]
Re: Pam stuff.

I have no idea why PAM discourages stack objects, but I wrote a simple mpv plugin once and stack objects were  the right thing to do there. Then again mpv plugins work a bit different: Their entry point function is supposed to have an event loop and only return when the plugin is finished.

**Comment by Leon-Plickat** [comment]
If we go that route, we'd need a `river_handle_t` to avoid having global variables.

**Comment by Leon-Plickat** [comment]
There should probably also be a user command to re-layout an output. That would enable external processes which may interface with the layout plugin to update the layout actively instead of re-actively.

**Comment by Leon-Plickat** [comment]
Also one last sanity check before actually commit to this: Are we **totally** sure the `dlopen()` approach makes more sense for layouts than the current approach or layout generators being Wayland clients?

**Comment by Leon-Plickat** [comment]
Closing, as we apparently figured out how we want to do it.

**Comment by phuhl** [comment]
Hi, I was looking into layout generation and was wondering how to get the app_id and especially the requsted size. This issue seems to address this but does not get into details on the solution. Is this implemented, is it planned? What is planned? Where could I get more infos?

Thanks

**Comment by Leon-Plickat** [comment]
We had this at one point, but discarded both the idea and the implementation.

The way layout generators work is planned to be redesigned eventually, but until then layouts are considered mostly feature complete.

**Comment by phuhl** [comment]
Ok, thanks for clarifying
