### ISSUE TITLE
wlroots next release todo

### ISSUE THREAD

**Issue by ifreund** [ifreund/river#117]
- remove duplicate protocol error code in river for layer shell: https://github.com/swaywm/wlroots/pull/2422

**Comment by maringuu** [comment]
* Remove https://github.com/ifreund/river/blob/30b1675fe82a07f5817afeebef74bd52e0584b84/river/Output.zig#L605-L607

**Comment by ifreund** [comment]
* Fix #89 using the new `wlr_layer_surface_v1_for_each_popup`

**Comment by ifreund** [comment]
These have all been implemented.
