### ISSUE TITLE
"Expected type '[]const u8'" errors while building with yay

### ISSUE THREAD

**Issue by agoodfellow123** [ifreund/river#119]
> Semantic Analysis [1964/2886] ./build.zig:142:41: error: expected type '[]const u8', found '(enum literal)'
>             .step = std.build.Step.init(.Custom, "Scan Protocols", builder.allocator, make),
>                                         ^
> ./build.zig:237:41: error: expected type '[]const u8', found '(enum literal)'
>             .step = std.build.Step.init(.Custom, "Generate man pages", builder.allocator, make),
>                                         ^
> ==> ERROR: A failure occurred in build().

kernel: 5.8.6-1-MANJARO

**Comment by ifreund** [comment]
Hello, it looks like you're using zig `0.6.0` to build river. As stated in the readme, river currently requires zig master to build (though it is planned to stick with `0.7.0` when it is released on the 26th).

**Comment by agoodfellow123** [comment]
Ah i see, i just want to let you know that i didn't had zig before river (as far as i can call) so river installed that version of zig itself, you may want to look into that. Thanks for the quick response. I'll look into it now.

**Comment by ifreund** [comment]
Well, I run void full time these days so maybe I should just orphan the AUR package... Anyways, issues with the AUR package belong in the comments of the AUR. Thanks for the heads up regardless.
