### ISSUE TITLE
Suggestions for new window commands.

### ISSUE THREAD

**Issue by lazy-dolphin** [ifreund/river#12]
- commands to move a window up and down the stack
- commands to spawn a window in a location next or previous to the currently focused window in the stack where the window to spawn is given as an argument.

**Comment by ifreund** [comment]
> commands to move a window up and down the stack

This seems like a very reasonable thing to add.

> commands to spawn a window in a location next or previous to the currently focused window in the stack where the window to spawn is given as an argument.

I think it makes most sense to implement this as an option determining where new views should be spawned. Taking inspiration from [dwm's patches](https://dwm.suckless.org/patches/), a list of possible values for an `attach` option might be:

- `top` (current behavior)
- `bottom` (spawn at the bottom of the stack)
- `above` (spawn above the current focus)
- `below` (spawn below the current focus)
- `aside` (spawn as the first non-master view)

**Comment by lazy-dolphin** [comment]
The reason for me suggesting separate spawn commands/arguments is that it is much more flexible than a setting to spawn all windows in a particular position. For instance, a use case for this would be mapping two different bindings to `spawning a terminal as a slave window` and `spawning a terminal as a master window`.

**Comment by ifreund** [comment]
this could also be done with
```sh
riverctl map Mod4 X spawn 'riverctl set-option attach top && alacritty'
riverctl map Mod4 Y spawn 'riverctl set-option attach aside && alacritty'
```
```

**Comment by ifreund** [comment]
`attach top|bottom` and `swap next|previous` have been implement. Possibly implementing more attach modes can be discussed in a new issue if necessary

**Comment by benbuch** [comment]
I can't figure out how to achieve this? How would I create a window next to master window? lets say am having firefox as the master window and now i want to spawn a new foot window and have the focus on this new foot window?

**Comment by benbuch** [comment]
that only works ones. the patch lazy-dolpin refers to https://dwm.suckless.org/patches/attachaside/ will keep spawning windows next to master and not just in the bottom of the stack

**Comment by novakne** [comment]
There is only the option to spawn to the top or the bottom of the stack in river
