### ISSUE TITLE
feature request: send zriver_seat_status_v1.focused_view when title of focused view changes.

### ISSUE THREAD

**Issue by Leon-Plickat** [ifreund/river#133]
This is needed if a bar wants to display the title of the focused window.

Then it may also make sense to rename it to `focused_view_title`, especially considering that the title is the only bit of data it provides.

And while not strictly necessary, I think it would make sense for it to also send a `wl_output`.

**Comment by ifreund** [comment]
Sending the event when the title changes makes total sense.

Not sure the rename is worth it as it would be a breaking change and we may add more bits of data aside from the title in the future.

I'm not sure we want to duplicate information and add a `wl_output` to the `focused_view` event. If we did so would we be able to get rid of the `focused_output` and `unfocused_output` events?

**Comment by Leon-Plickat** [comment]
In that case let's keep the name and leave `wl_output` out of the event.

RE: other data: It might make sense to also send the shell, the app_id and the floating status.

**Comment by Leon-Plickat** [comment]
Submitted a PR, so I am going to close this issue.
