### ISSUE TITLE
zig build binaries fail

### ISSUE THREAD

**Issue by icarus4xu** [ifreund/river#145]
$ zig build -Drelease-safe=true --prefix /usr/local install

Semantic Analysis [1834/2835] ./deps/zig-wayland/build.zig:49:35: error: expected type '[]const u8', found '(enum literal)'
            .step = zbs.Step.init(.Custom, "Scan Protocols", builder.allocator, make),
                                  ^
./build.zig:150:41: error: expected type '[]const u8', found '(enum literal)'
            .step = std.build.Step.init(.Custom, "Scan Protocols", builder.allocator, make),
                                        ^
./build.zig:247:41: error: expected type '[]const u8', found '(enum literal)'
            .step = std.build.Step.init(.Custom, "Generate man pages", builder.allocator, make),

**Comment by VojtechStep** [comment]
What version of Zig are you running?

**Comment by ifreund** [comment]
This is exactly the error you get if you try and build river with zig 0.6.0, does zig master work for you? Note that river will stick with zig 0.7.0 when it is released shortly.

**Comment by ifreund** [comment]
Closing as stale, feel free to reopen if you still have trouble building river with zig 0.7.0
