### ISSUE TITLE
Install example config to /etc/river/init

### ISSUE THREAD

**Issue by daurnimator** [ifreund/river#146]
To help new users get started it would be helpful to ship an example config which users could use to derive their own.

**Comment by Leon-Plickat** [comment]
Errr... isn't `contrib/config.sh` exactly that?

**Comment by ifreund** [comment]
`contrib` usually is for stuff that should not be included when packaging a program. This issue can be closed when we move the example config from contrib to doc and install it to `/etc/river/whatever` in our build.zig.

**Comment by ifreund** [comment]
Implemented in c7bc47d6d4ca11ad0cc3a0216b8e45d232fc30fa
