### ISSUE TITLE
Default location for startup script

### ISSUE THREAD

**Issue by daurnimator** [ifreund/river#147]
Add a default location to look for startup scripts, e.g. `~/.config/river/startup`
Possibly falling back to `/etc/river/startup`.

**Comment by ifreund** [comment]
If we do this we should probably respect `$XDG_CONFIG_HOME` as well. I'm thinking that this is an acceptable level of additional complexity over just having the command line flag but I'll have to think a bit on what I want the name to be.

**Comment by Leon-Plickat** [comment]
In that case I recommend explicitly not using any extensions like `.sh` for the default path, people may use something other than a shell script.

**Comment by ifreund** [comment]
> In that case I recommend explicitly not using any extensions like `.sh` for the default path, people may use something other than a shell script.

Agreed, my favorite so far is `~/.config/river/init`.

**Comment by ifreund** [comment]
Implemented in #152
