### ISSUE TITLE
shiftview option

### ISSUE THREAD

**Issue by sillypill** [ifreund/river#150]
Basically an option to cycle view through the tags. If multiple tags are selected, shift all the selected tags.
In other words, an option to perform a circular shift to the current vew-tags tagmask.

On an unrelated note, I've been using river (almost) as a daily driver for the past 2 days and absolutely love it! Thank you for all the work on the project!

**Comment by Leon-Plickat** [comment]
I say It would make more sense to simply expose the tag of the currently focused view in zriver_seat_status_v1.focused_view. Then you could just write that functionality yourself.

**Comment by sillypill** [comment]
That makes sense to me. Okay.
