### ISSUE TITLE
Questions regarding this project?

### ISSUE THREAD

**Issue by Joe23232** [ifreund/river#151]
I have a few questions regarding this project.

1. Does it have window decoration support? For example
![Full window (options)](https://user-images.githubusercontent.com/34926497/99211116-b7559780-281b-11eb-9c47-9b59782df827.png)

If not then does it plan to implement it? 

2. Does it come with its own taskbar and gadgets?
3. Am I able to use this to create my own lockscreen as well?
4. Is it like `dwm` where I add code in a high level manner and then I recompile the entire project?
5. If 4 is true, then whatever file I code in it, is there minimal amount of code and is it straight forward unlike `awesome` WM?

**Comment by Leon-Plickat** [comment]
> 1. Does it have window decoration support? For example

River can draw a simple border around windows, but nothing fancy. I don't think anything more fancy planned.

> 2. Does it come with its own taskbar and gadgets?
> 3. Am I able to use this to create my own lockscreen as well?

River is not awesomewm. It includes absolutely no desktop widgets and is definitely not a scriptable application framework.

You'll have to use external applications for these things.

> 4. Is it like dwm where I add code in a high level manner and then I recompile the entire project?

River luckily does not follow dwms weird development model. You compile it once. Either something is included, or it is not, no patches. Configuration is done with riverctl at runtime.

**Comment by Joe23232** [comment]
I see, thanks guys.

**Comment by ifreund** [comment]
closing as the questions have been answered. You may want to check out this wiki page for related software https://github.com/ifreund/river/wiki/Recommended-Software
