### ISSUE TITLE
Add an option to set wlroots log level

### ISSUE THREAD

**Issue by maringuu** [ifreund/river#154]
Sometimes during development it can be useful to set wlroots logging to `WLR_DEBUG` or any other log level.
In wlroots we have 4 log levels and in zig we have 7 so probably it would be good to add add change the `-l` argument to accept two values. Maybe in the format `river_log_level[:optional_wlroots_log_level]`.

The default would be to just log `WLR_ERROR`

Any opinions on this?

https://github.com/swaywm/wlroots/blob/6284af121fd1427eaefb043ea03363c969f2df3f/include/wlr/util/log.h#L25-L30

**Comment by ifreund** [comment]
can we just tie it to the river log level? I don't see a good reason to have a separate option

**Comment by maringuu** [comment]
Yeah. My reasoning was that they are currently untied (but ofc can't be changed) and our log levels dont map 1:1 to wlroots log levels.

**Comment by ifreund** [comment]
They don't map 1:1 but they should map well enough:
```zig
switch (log_level) {
    .debug => .wlr_debug,
    .notice, .info, => .wlr_info,
    .warn, .error, .crit, .alert, .emerg => .wlr_err,
}
```
