### ISSUE TITLE
Keyboard repeat info lost on VT switch

### ISSUE THREAD

**Issue by Bonicgamer** [ifreund/river#163]
Switching to a VT and back makes it so that the keyboard repeat rate and delay is reset, and if you try to set it again River crashes.

Sway does something with a wl_event_source called "key_repeat_source" which sounds like its related, but I don't actually know.

**Comment by ifreund** [comment]
fixed the crash in 807d4a4212a2cc14203d63376895cc36072ff1a2. We need a slightly different architecture to "remember" the repeat info across keyboard destruction/recreation.

**Comment by ifreund** [comment]
Fixed in 1732c694428e274280cbdbf1032a6bfed2586b5d
