### ISSUE TITLE
Xwayland crash

### ISSUE THREAD

**Issue by travankor** [ifreund/river#164]
Runnning glxdemo from mesa-demos causes river to reproducibly crash.

```
Segmentation fault at address 0x14
/home/travankor/git/river/river/XwaylandView.zig:174:40: 0x23a6c6 in XwaylandView.handleMap (river)
    const has_fixed_size = size_hints.*.min_width != 0 and size_hints.*.min_height != 0 and
```

**Comment by Leon-Plickat** [comment]
Tried to reproduce and interestingly for me it is glxdemo that crashes reliably in river.

Anyway, from the error message I suspect that glxdemo may not set sizehints (such demo clients are notorious for doing only the bare minimum to get a window running). Just checked the code in river and apparently it is never checked whether the sizehints pointer we get from `wlr_xwayland_surface.size_hints` is valid.

**Comment by ifreund** [comment]
Thanks for the investigation, this should already be fixed on the `zig-wlroots` branch then (yay optional pointers) https://github.com/ifreund/river/blob/799972ca111a1f7161e233ed0d16854479ea8828/river/XwaylandView.zig#L172-L176
