### ISSUE TITLE
Errors when building on Fedora 33

### ISSUE THREAD

**Issue by bspookey** [ifreund/river#166]
Hi all, this is what I'm getting on Fedora 33:

$ sudo zig build -Drelease-safe=true --prefix /usr/local/ install
./build.zig:3:27: error: unable to find 'deps/zig-wayland/build.zig'
const ScanProtocolsStep = @import("deps/zig-wayland/build.zig").ScanProtocolsStep;
                          ^
./build.zig:43:21: note: referenced here
    const scanner = ScanProtocolsStep.create(b, "deps/zig-wayland/");
                    ^
/usr/lib/zig/std/special/build_runner.zig:147:24: note: referenced here
        .ErrorUnion => try root.build(builder),

Confirmed that all dependencies in the README are met. Only thing is Fedora does not have an official zig package in their repository so I am using a copr for that: https://copr.fedorainfracloud.org/coprs/sentry/zig/

**Comment by bspookey** [comment]
Guess I did miss something:
git submodule update --init

DOH! I'm closing this issue.

**Comment by Vintodrimmer** [comment]
I also have a build issue on Fedora 33, except with a different error:

```
zig build -Dxwayland -Drelease-safe --prefix /usr install
./river/main.zig:71:50: error: no member named 'outStream' in struct 'std.fs.file.File'
                const stdout = std.io.getStdOut().outStream();
                                                 ^
river...The following command exited with error code 1:
/usr/bin/zig build-exe /tmp/river/river/main.zig -lc -levdev -lwayland-server -lxkbcommon -lpixman-1 -lwlroots -cflags -std=c99 -- /tmp/river/zig-cache/zig-wayland/{ 120, 100, 103, 45, 115, 104, 101, 108, 108 }-protocol.c -cflags -std=c99 -- /tmp/river/zig-cache/zig-wayland/{ 120, 100, 103, 45, 111, 117, 116, 112, 117, 116, 45, 117, 110, 115, 116, 97, 98, 108, 101, 45, 118, 49 }-protocol.c -cflags -std=c99 -- /tmp/river/zig-cache/zig-wayland/{ 114, 105, 118, 101, 114, 45, 99, 111, 110, 116, 114, 111, 108, 45, 117, 110, 115, 116, 97, 98, 108, 101, 45, 118, 49 }-protocol.c -cflags -std=c99 -- /tmp/river/zig-cache/zig-wayland/{ 114, 105, 118, 101, 114, 45, 111, 112, 116, 105, 111, 110, 115, 45, 117, 110, 115, 116, 97, 98, 108, 101, 45, 118, 49 }-protocol.c -cflags -std=c99 -- /tmp/river/zig-cache/zig-wayland/{ 114, 105, 118, 101, 114, 45, 115, 116, 97, 116, 117, 115, 45, 117, 110, 115, 116, 97, 98, 108, 101, 45, 118, 49 }-protocol.c -cflags -std=c99 -- /tmp/river/zig-cache/zig-wayland/{ 119, 108, 114, 45, 108, 97, 121, 101, 114, 45, 115, 104, 101, 108, 108, 45, 117, 110, 115, 116, 97, 98, 108, 101, 45, 118, 49 }-protocol.c -cflags -std=c99 -- /tmp/river/zig-cache/zig-wayland/{ 119, 108, 114, 45, 111, 117, 116, 112, 117, 116, 45, 112, 111, 119, 101, 114, 45, 109, 97, 110, 97, 103, 101, 109, 101, 110, 116, 45, 117, 110, 115, 116, 97, 98, 108, 101, 45, 118, 49 }-protocol.c --pkg-begin build_options /tmp/river/zig-cache/river_build_options.zig --pkg-end -OReleaseSafe --cache-dir /tmp/river/zig-cache --global-cache-dir /root/.cache/zig --name river --pkg-begin wayland /tmp/river/zig-cache/zig-wayland/wayland.zig --pkg-end --pkg-begin xkbcommon /tmp/river/deps/zig-xkbcommon/src/xkbcommon.zig --pkg-end --pkg-begin pixman /tmp/river/deps/zig-pixman/pixman.zig --pkg-end --pkg-begin wlroots /tmp/river/deps/zig-wlroots/src/wlroots.zig --pkg-begin wayland /tmp/river/zig-cache/zig-wayland/wayland.zig --pkg-end --pkg-begin xkbcommon /tmp/river/deps/zig-xkbcommon/src/xkbcommon.zig --pkg-end --pkg-begin pixman /tmp/river/deps/zig-pixman/pixman.zig --pkg-end --pkg-end -I /usr/include/libevdev-1.0 -I /usr/include/pixman-1 -I /usr/include/libdrm -I /usr/include/pixman-1 -I /usr/include/uuid --enable-cache
error: the following build command failed with exit code 1:
/tmp/river/zig-cache/o/27b6dde842ea866374319ea5c5e05e1a/build /usr/bin/zig /tmp/river /tmp/river/zig-cache /root/.cache/zig -Dxwayland -Drelease-safe --prefix /usr install
```
I'm using the same copr and am fairly certain all the dependencies are installed.
Have any idea what it may be?

**Comment by ifreund** [comment]
> I also have a build issue on Fedora 33, except with a different error:
> 
> ```
> zig build -Dxwayland -Drelease-safe --prefix /usr install
> ./river/main.zig:71:50: error: no member named 'outStream' in struct 'std.fs.file.File'
>                 const stdout = std.io.getStdOut().outStream();
>                                                  ^
> river...The following command exited with error code 1:
> /usr/bin/zig build-exe /tmp/river/river/main.zig -lc -levdev -lwayland-server -lxkbcommon -lpixman-1 -lwlroots -cflags -std=c99 -- /tmp/river/zig-cache/zig-wayland/{ 120, 100, 103, 45, 115, 104, 101, 108, 108 }-protocol.c -cflags -std=c99 -- /tmp/river/zig-cache/zig-wayland/{ 120, 100, 103, 45, 111, 117, 116, 112, 117, 116, 45, 117, 110, 115, 116, 97, 98, 108, 101, 45, 118, 49 }-protocol.c -cflags -std=c99 -- /tmp/river/zig-cache/zig-wayland/{ 114, 105, 118, 101, 114, 45, 99, 111, 110, 116, 114, 111, 108, 45, 117, 110, 115, 116, 97, 98, 108, 101, 45, 118, 49 }-protocol.c -cflags -std=c99 -- /tmp/river/zig-cache/zig-wayland/{ 114, 105, 118, 101, 114, 45, 111, 112, 116, 105, 111, 110, 115, 45, 117, 110, 115, 116, 97, 98, 108, 101, 45, 118, 49 }-protocol.c -cflags -std=c99 -- /tmp/river/zig-cache/zig-wayland/{ 114, 105, 118, 101, 114, 45, 115, 116, 97, 116, 117, 115, 45, 117, 110, 115, 116, 97, 98, 108, 101, 45, 118, 49 }-protocol.c -cflags -std=c99 -- /tmp/river/zig-cache/zig-wayland/{ 119, 108, 114, 45, 108, 97, 121, 101, 114, 45, 115, 104, 101, 108, 108, 45, 117, 110, 115, 116, 97, 98, 108, 101, 45, 118, 49 }-protocol.c -cflags -std=c99 -- /tmp/river/zig-cache/zig-wayland/{ 119, 108, 114, 45, 111, 117, 116, 112, 117, 116, 45, 112, 111, 119, 101, 114, 45, 109, 97, 110, 97, 103, 101, 109, 101, 110, 116, 45, 117, 110, 115, 116, 97, 98, 108, 101, 45, 118, 49 }-protocol.c --pkg-begin build_options /tmp/river/zig-cache/river_build_options.zig --pkg-end -OReleaseSafe --cache-dir /tmp/river/zig-cache --global-cache-dir /root/.cache/zig --name river --pkg-begin wayland /tmp/river/zig-cache/zig-wayland/wayland.zig --pkg-end --pkg-begin xkbcommon /tmp/river/deps/zig-xkbcommon/src/xkbcommon.zig --pkg-end --pkg-begin pixman /tmp/river/deps/zig-pixman/pixman.zig --pkg-end --pkg-begin wlroots /tmp/river/deps/zig-wlroots/src/wlroots.zig --pkg-begin wayland /tmp/river/zig-cache/zig-wayland/wayland.zig --pkg-end --pkg-begin xkbcommon /tmp/river/deps/zig-xkbcommon/src/xkbcommon.zig --pkg-end --pkg-begin pixman /tmp/river/deps/zig-pixman/pixman.zig --pkg-end --pkg-end -I /usr/include/libevdev-1.0 -I /usr/include/pixman-1 -I /usr/include/libdrm -I /usr/include/pixman-1 -I /usr/include/uuid --enable-cache
> error: the following build command failed with exit code 1:
> /tmp/river/zig-cache/o/27b6dde842ea866374319ea5c5e05e1a/build /usr/bin/zig /tmp/river /tmp/river/zig-cache /root/.cache/zig -Dxwayland -Drelease-safe --prefix /usr install
> ```
> 
> I'm using the same copr and am fairly certain all the dependencies are installed.
> Have any idea what it may be?

Looks like you are not using zig 0.7.1 but a more recent master build.

**Comment by Vintodrimmer** [comment]
Thanks, think this might be it.
The version in the copr is "zig-0.7.1-4.0cfa39304".
