### ISSUE TITLE
Xwayland is not found although it is in PATH

### ISSUE THREAD

**Issue by maringuu** [ifreund/river#168]
This might be related to musl and gcompat.

Steps to reproduce:
1. compile river with `-Dxwayland`
2. Start river

```
$ which Xwayland
/usr/bin/Xwayland
```

The [logs](https://paste.sr.ht/~maringuu/d7ca0e7912573cdacd239cc884be066550878a73) are the same as in #167

**Comment by ifreund** [comment]
This is entirely handled by wlroots, execvp is called here so I'm not sure what the issue could be: https://github.com/swaywm/wlroots/blob/e69bbfd0d6a654a0421793bf10cb3cab15e13273/xwayland/server.c#L120

**Comment by maringuu** [comment]
@ifreund Thanks for investigation.
Can you reproduce?

**Comment by ifreund** [comment]
> Can you reproduce?

Nope, it works fine for me on a glibc voidlinux install.

**Comment by maringuu** [comment]
The problem is somewhere in gcompat and unrelated to river.
When I set the interpreter of my river binary with `patchelf --set-interpreter /lib/ld-musl-x86_64.so.1` it does work.
