### ISSUE TITLE
Scratchpad

### ISSUE THREAD

**Issue by maringuu** [ifreund/river#169]
These are two things I heavily used in sway. It would be nice if there was a way to do them with river.

## Sticky views
~A sticky view is a view that is always visible. Commonly sticky views are floating.~
~My idea was to give sticky views a specific tag.
Lets say I have tags with values `0b001`and `0b010`. To implement sticky views I introduced a tag `0b100`. All sticky views would go to this tag.
My old config~
```
# The 0b is just for better explanation
riverctl map $mod 1 set-focused-tags 0b001
riverctl map $mod 2 set-focused-tags 0b010
```
~would then become~
```
riverctl map $mod 1 set-focused-tags 0b101
riverctl map $mod 2 set-focused-tags 0b110

# Make view sticky
riverctl map $mod S set-view-tags 0b100
```

~The problem is that all applications that are spawned inherit the current view tags and thus would also be sticky~

Edit: I thought the wrong way around. This is already possible.

## Ranger as an application opener
When I used sway I always opened a terminal with `ranger` in it. This terminal would go to the scratchpad.
When I wanted to open a pdf on my _current_ workspace I showed the scratchpad, opened the pdf and then hid my terminal with ranger.

When implementing a simelar behavior in river I face the same problem as with sticky views. Newly spawned windows would always be part of the scratchpad.

# Proposed solution
Both usecases are solved by being able to set the tagmasks that new views will have.
Something like `riverctl set-spawn-tags` and `riverctl toggle-spawn-tags`.

What are your thoughts?

**Comment by Leon-Plickat** [comment]
> Sticky views

Don't we already have that functionality? If you set the tags of a view to `111111111`, all on, than it will appear no matter what tags are focused. It is effectively sticky. Or am I missing something?

**Comment by maringuu** [comment]
Good point. I didn't think of that.

**Comment by ifreund** [comment]
I think 30ba87fa1531d6accf223552d7e65955e1434537 concludes this issue.
