### ISSUE TITLE
Cursor doesn't stay on xwayland windows when moving them.

### ISSUE THREAD

**Issue by Bonicgamer** [ifreund/river#173]
When moving a xwayland window across the screen the cursor goes off the window.

I believe the problem is that the view.current.box.x and y isn't always equal to the xwayland_surface.x and y.

Here's an example of me printing the values while moving a window around:
```
current.box.x: '376'
xwayland_surface.x: '294'
current.box.y: '418'
xwayland_surface.y: '496'
```

Having the cursor to move based off of the xwayland_surface instead of view.current.box fixes the problem.

**Comment by ifreund** [comment]
Fixed in a098bbe03abf5fc7f67d817af1445def53ac02e7
