### ISSUE TITLE
Move cursor to new output automatically on focus-output command

### ISSUE THREAD

**Issue by snakedye** [ifreund/river#178]
The focus should follow the cursor and the cursor should follow the output.

ex. If I move my cursor to another monitor and have focus_follows_cursor set to normal, the window my mouse is hovering over should be focused. I shouldn't have to manually switch output to focus it.

ex. If I switch outputs, my mouse should (at least have the option) be repositioned to the chosen output.

**Comment by ifreund** [comment]
Was this not implemented in 49bf0e679ff42226a5a1ba8b3750dac1b2501f3b?

**Comment by Leon-Plickat** [comment]
> Was this not implemented in 49bf0e6?

The first part yes, but the second part not. We have a "focus follow cursor" mode, but no "cursor follow focus" functionality. There are many ways that could work, but at the very least we should have an option to let the cursor be warped when the output-focus is changed.

If no one else picks it up, I'll do it when I am finished with #112

**Comment by ifreund** [comment]
Changed the title to better reflect what this issue is asking for. How would we determine where to put the cursor on the new output? Just center it?

**Comment by snakedye** [comment]
center is just fine
