### ISSUE TITLE
default init script doesn't run when installing to a different prefix

### ISSUE THREAD

**Issue by AlexJMohr** [ifreund/river#179]
I built river and installed to ~/.local. When I ran it, I noticed none of the keybinds were set. Looks like river looks for `init` in `XDG_CONFIG_HOME`, `HOME`, then `/etc`. Maybe the install prefix should be added to the places to look, or it should replace the `/etc` fallback. I'd be happy to have a go at implementing this and submit a PR.

### Steps

1. `zig build install --prefix=$HOME/.local` or anywhere else
2. run `~/.local/bin/river`
3. try using any keybind

**Comment by ifreund** [comment]
Indeed, we should use the location the default config was actually installed to, not `/etc/river/init`. Implementation-wise we should probably add `default_config_path` as a build option for the river executable with `LibExeObjStep.addBuildOption()`. See how this is done for xwayland currently.

**Comment by ifreund** [comment]
Implemented in 75588a553c9eaaa7aa50c96c03cb7b15ffb4955b
