### ISSUE TITLE
Popup menu doesn't get positioned correctly for Xwayland apps and GTK apps on multi monitors

### ISSUE THREAD

**Issue by FollieHiyuki** [ifreund/river#182]
This only happens for a multi monitors setup, and for only the farthest outputs to the right (virtually).
Popups (tooltips, right click menus, drop-down menus) for Xwayland applications get drawn on the left output while the ones for GTK apps (native wayland) get drawn out of the screen to the right.

I only use 2 monitors, and that is what I see. I will try to see how it behaves on 3 monitors later.

**Comment by ifreund** [comment]
Fixed for wayland clients in e7442e53c1bb31b10bcb94a499431a2819e16769. The issue still remains for Xwayland clients

**Comment by ifreund** [comment]
Fixed for xwayland as well in 7249f5c9c3f32462a675fc6888bc4dd5f1e83845
