### ISSUE TITLE
Borders are drawn above popups

### ISSUE THREAD

**Issue by FollieHiyuki** [ifreund/river#184]
![screenshot](https://user-images.githubusercontent.com/67634026/103596987-3a3bca00-4f10-11eb-985b-771481dc0c76.png)

It only happens for Wayland native apps.

**Comment by Leon-Plickat** [comment]
Happens because toplevel surfaces and popup surfaces are rendered before the border.

Maybe we should just render borders first and risk the odd misbehaving application drawing stuff over them.

**Comment by ifreund** [comment]
Fixed in b73cb7bb6993076c0bd794df342fe8516a082a96
