### ISSUE TITLE
focus-follows-cursor normal fails when moving between outputs

### ISSUE THREAD

**Issue by edrex** [ifreund/river#185]
When moving across outputs, the first view encountered in the new output doesn't get focused.

I think this is eluded to by @snakedye in #178, but it's a seperate issue.

Also, hi :) I just moved over from sway and my 15yo awesomewm muscle memory came right back :D

**Comment by edrex** [comment]
Switching to focus-follows-cursor strict is a workaround

**Comment by ifreund** [comment]
Hi and welcome!

Could you confirm that #191 fixes this issue? I don't have a second monitor to test this properly at the moment.

**Comment by edrex** [comment]
Tested #191 and `focus-follows-cursor normal` seems to work as expected across monitors now. Thanks!
