### ISSUE TITLE
The command for bottom layout in the init file example is wrong.

### ISSUE THREAD

**Issue by FoundOne** [ifreund/river#187]
It should be:
`riverctl map normal $mod Down layout rivertile bottom`
rather than:
`riverctl map normal $mod Down layout rivertile down`

Also, I think the layout manager should warn when the there is no such layout instead of defaulting to full.

**Comment by ifreund** [comment]
Fixed in faca330bd05fc2d2c8f175fa3d3f068af6f1fbbe. The way layouts work will be changing shortly in #112 so I'm not going to bother with an error for now.
