### ISSUE TITLE
The the context menu in Firefox does not show anymore.

### ISSUE THREAD

**Issue by FoundOne** [ifreund/river#188]
The right click menu does not appear for me anymore. It gets activated though, because I can't scroll down anymore until I don't click or hit escape. Also, the right click event works, because script menus in Youtube
for an example are fully working.

platform: Manjaro-arm unstable RK3399
river-git r533.751b63f-1

**Comment by ifreund** [comment]
As far as I can tell, popups work in everything except firefox. This should be fun to debug :/

**Comment by ifreund** [comment]
This is fixed by https://github.com/swaywm/wlroots/pull/2609

**Comment by ifreund** [comment]
Apparently not so much of a bug with wlroots as a design flaw which will hopefully be fixed by the next release (I've opened PRs). I implemented a workaround (a672738) in river to fix this for now though so we can close this.
