### ISSUE TITLE
How config river to open program in layout?

### ISSUE THREAD

**Issue by n1rdeks** [ifreund/river#190]
How config river init file for open firefox in layout 2 (tag)?

for example, DWM:
    /* class      instance    title       tags mask     isfloating   monitor */
    { "firefox",     NULL,     NULL,       1 << 1,       0,           -1}

**Comment by Leon-Plickat** [comment]
You don't, because that feature does not exist yet.

If you want river to have this feature, either implement it yourself or make (and discuss) a proposal.

**Comment by n1rdeks** [comment]
thx. Well, maybe need create acc on freenode...
