### ISSUE TITLE
Initial layout for displays unfocused at startup or hotplugged

### ISSUE THREAD

**Issue by edrex** [ifreund/river#192]
Currently with the example init only the primary output gets an initial layout on startup. On other display windows just stack up. Not sure how to make it better, but seems like either documenting a good way to handle this in the startup script or adding a default layout to the protocol maybe?

**Comment by edrex** [comment]
this is pretty trivial and I don't have a good suggestion, feel free to close.

**Comment by Leon-Plickat** [comment]
Wouldn't close this just yet, as that is an actual problem: There is no way to set defaults for new outputs. For layout this is pretty annoying, because you have to manually focus the output and execute riverctl. And #112 does not solve this.

The best solutions, IMO, is making riverctl commands which change the state of an output to specify the target output. Like `riverctl HDMI-A-1 layout tile`.

**Comment by Leon-Plickat** [comment]
(By the way, small nit-pick: River does not have the concept of a "primary display". That is an X thing. When the init file gets executed, its commands affect the currently focused output. The output that is focused on startup before the init file is executed is simply the first output river found. Try changing the output focus in the init file, which will cause the other output to be affected.)

**Comment by edrex** [comment]
this could be used with kanshi's `exec` directive to set layouts per profile too

**Comment by FollieHiyuki** [comment]
I only use 1 layout (mostly), so for the startup I work around by putting this into `init` file
```
i=0
while [ $i -le $(wlr-randr | grep -c "\"*.\"") ]
do
    # Set the layout on startup
    riverctl layout rivertile left

    # New view starts at bottom
    riverctl attach-mode bottom

    riverctl focus-output next
    i=$(( i + 1 ))
done
```

**Comment by edrex** [comment]
yeah, i though about just cycling through with focus-output next but I hot plug the second display a lot

**Comment by ifreund** [comment]
This is no longer an issue with `river-options-v2`

**Comment by ideasman42** [comment]
It would be good if there was some information about how to set the layout, a link to the docs - or some hint for what to look for to set the layout on new monitors.
