### ISSUE TITLE
multiple outputs: slurp crashes river

### ISSUE THREAD

**Issue by edrex** [ifreund/river#194]
When I attempted to select a region with [slurp](https://github.com/emersion/slurp) using my [screenshot](https://github.com/edrex/dotfiles/blob/master/bin/screenshot) script, river crashes.

It only happens with multiple outputs. Also, if I hotplug the second output, selections on the first don't trigger a crash. Maybe selections on the first always work; not sure because I only tried once and maybe the order isn't deterministic.

`❯ coredumpctl info | pb`
https://clbin.com/8runF

**Comment by ifreund** [comment]
I think 41e5206 fixes this, or at least I can't reproduce in a multi-output nested session anymore. Could you confirm?

**Comment by edrex** [comment]
Can confirm, that commit fixed it! Thanks!
