### ISSUE TITLE
qutebrowser <select> popup contents not scaled (multiple outputs, scaled, translated)

### ISSUE THREAD

**Issue by edrex** [ifreund/river#195]
With a 2x scaled, offset, sibling output, the contents of qutebrowser select popups aren't scaled down, and the view seems to be of the bottom-right quad of the surface (although it might also be some function of the output offset, not sure).

This doesn't happen:
 - If the output is at `pos 0,0`
 - If the output scale is `1`
 - If only one output is connected (maybe because `pos` is ignored then)

I'll attach a screenshot when I can.

**Comment by edrex** [comment]
Not sure is those selects are native Qt or Chromium widgets. Tried to test with other qt apps but didn't readily find one that uses Wayland and has selects. Also I don't have the new wayland native Chromium installed atm.

**Comment by edrex** [comment]
Scale 1 screen: 
![Screenshot-2021-01-09-13:22:33](https://user-images.githubusercontent.com/14615/104109016-a86ced80-527e-11eb-9360-6413c0330cc0.png)

Scale 2 screen with pos 0,0:
![Screenshot-2021-01-09-13:47:39](https://user-images.githubusercontent.com/14615/104109313-7610bf80-5281-11eb-8645-1e764fa9f43d.png)

Scale 2 screen with offset:
![Screenshot-2021-01-09-13:25:52](https://user-images.githubusercontent.com/14615/104109017-aacf4780-527e-11eb-8574-02831791a2d1.png)

Need to test if this happens in sway.

**Comment by edrex** [comment]
I noticed another weird criteria for this bug to be triggered: if the select popup is in the right third or so of the hi-dpi display it will be displayed normally.

**Comment by edrex** [comment]
@The-Compiler i think this is on the compositor side but FYI

**Comment by The-Compiler** [comment]
Might be a bug in QtWebEngine as well - certainly wouldn't be the first `<select>` HighDPI bug... If you want another QtWebEngine application to try, KDE Falkon is probably the easiest.

**Comment by edrex** [comment]
Ok so i just tested in sway and this happens there too, so at least definitely not river-specific, and likely a Qt issue. Should have tested that sooner, sorry :)
