### ISSUE TITLE
second output freezes sometimes

### ISSUE THREAD

**Issue by edrex** [ifreund/river#196]
Sometimes the second (external) display will stop updating, and just show the last frame.

 - Cursor doesn't show when moving mouse there, but the coordinate region still exists
 - I can send windows there and get them back

Toggling the output with `wlr-randr --output DP-1 --off ; wlr-randr --output DP-1 --on` or un/replug restores rendering to the output.

This time I had recently used [albertlauncher](https://github.com/albertlauncher/albert) to launch Nautilus but not sure how close in time that was. In the frozen frame the Nautilus view is a bit wider than requested, and is transparently overlapping a couple of foot terminals.

The [log](https://clbin.com/M8AAS) line 

```
[ERROR] [backend/drm/atomic.c:36] DP-1: Atomic commit failed (pageflip): Device or resource busy
```

around that time seems likely related.

 - Intel graphics, can attach more hwinfo if needed.

**Comment by edrex** [comment]
Happened again, also with a nautilus view on screen overlapping transparently with foot views, also with log lines

```
[ERROR] [backend/drm/atomic.c:36] DP-1: Atomic commit failed (pageflip): Device or resource busy
err: (render) output commit failed for DP-1^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
```

**Comment by maringuu** [comment]
Seems to be the same as #153

**Comment by edrex** [comment]
Oops, should have searched more first. Thanks!

**Comment by edrex** [comment]
[wlroots/atomic.c at c94728b53ade17d152ba1f600475140660db7a75 · swaywm/wlroots](https://github.com/swaywm/wlroots/blob/c94728b53ade17d152ba1f600475140660db7a75/backend/drm/atomic.c#L35)

**Comment by maringuu** [comment]
Thanks for report! It is good to have someone else who can reproduce this.

Note to self:  It seems that the output does not send frame events after freezing.
