### ISSUE TITLE
Get rid of log.zig, use std.log

### ISSUE THREAD

**Issue by ifreund** [ifreund/river#197]
This has been in the std since 0.7.0 but I haven't had a chance to switch to it yet. If anyone wants to give this a shot, be my guest.

**Comment by Leon-Plickat** [comment]
Is there a  reason we don't just use wlroots log functions?

**Comment by ifreund** [comment]
> Is there a reason we don't just use wlroots log functions?

Indeed, I'd rather use the formatting functions from the zig standard library than printf format specifiers.

**Comment by foxfromabyss** [comment]
Solved by #212 I think
