### ISSUE TITLE
build error -  undefined symbol: wlr_xdg_surface_for_each_popup

### ISSUE THREAD

**Issue by ekollof** [ifreund/river#198]
ld.lld: error: undefined symbol: wlr_xdg_surface_for_each_popup
>>> referenced by xdg_shell.zig:325 (/home/ekollof/Code/river/deps/zig-wlroots/src/types/xdg_shell.zig:325)
>>>               /home/ekollof/Code/river/zig-cache/o/719f0f376a49b710acaae186aba69034/river.o:(render.renderViewPopups)

ld.lld: error: undefined symbol: wlr_layer_surface_v1_for_each_popup
>>> referenced by layer_shell_v1.zig:123 (/home/ekollof/Code/river/deps/zig-wlroots/src/types/layer_shell_v1.zig:123)
>>>               /home/ekollof/Code/river/zig-cache/o/719f0f376a49b710acaae186aba69034/river.o:(render.renderLayer)
error: LLDReportedFailure
river...The following command exited with error code 1:
/usr/bin/zig build-exe /home/ekollof/Code/river/river/main.zig --library c --library evdev --library wayland-server --library xkbcommon --library pixman-1 --library wlroots -cflags -std=c99 -- /home/ekollof/Code/river/zig-cache/zig-wayland/xdg-shell-protocol.c -cflags -std=c99 -- /home/ekollof/Code/river/zig-cache/zig-wayland/river-control-unstable-v1-protocol.c -cflags -std=c99 -- /home/ekollof/Code/river/zig-cache/zig-wayland/river-status-unstable-v1-protocol.c -cflags -std=c99 -- /home/ekollof/Code/river/zig-cache/zig-wayland/wlr-layer-shell-unstable-v1-protocol.c -cflags -std=c99 -- /home/ekollof/Code/river/zig-cache/zig-wayland/wlr-output-power-management-unstable-v1-protocol.c --pkg-begin build_options /home/ekollof/Code/river/zig-cache/river_build_options.zig --pkg-end --cache-dir /home/ekollof/Code/river/zig-cache --global-cache-dir /home/ekollof/.cache/zig --name river --pkg-begin wayland /home/ekollof/Code/river/zig-cache/zig-wayland/wayland.zig --pkg-end --pkg-begin xkbcommon /home/ekollof/Code/river/deps/zig-xkbcommon/src/xkbcommon.zig --pkg-end --pkg-begin pixman /home/ekollof/Code/river/deps/zig-pixman/pixman.zig --pkg-end --pkg-begin wlroots /home/ekollof/Code/river/deps/zig-wlroots/src/wlroots.zig --pkg-begin wayland /home/ekollof/Code/river/zig-cache/zig-wayland/wayland.zig --pkg-end --pkg-begin xkbcommon /home/ekollof/Code/river/deps/zig-xkbcommon/src/xkbcommon.zig --pkg-end --pkg-begin pixman /home/ekollof/Code/river/deps/zig-pixman/pixman.zig --pkg-end --pkg-end -I /usr/include/libevdev-1.0 -I /usr/include/pixman-1 -I /usr/include/libdrm -I /usr/include/pixman-1 -I /usr/include/uuid --enable-cache
error: the following build command failed with exit code 1:
/home/ekollof/Code/river/zig-cache/o/56e3dc09d8fd5993a11bf57167546664/build /usr/bin/zig /home/ekollof/Code/river /home/ekollof/Code/river/zig-cache /home/ekollof/.cache/zig

**Comment by ifreund** [comment]
@ekollof I believe you are using the master branch of wlroots. River requires 0.12.0

**Comment by ekollof** [comment]
yep, that was the problem.
