### ISSUE TITLE
Implement pointer-constraints-v1 and relative-pointer-v1

### ISSUE THREAD

**Issue by FoundOne** [ifreund/river#200]
The mouse cursor makes weird turns, when it goes too much up or down and locks up in that motion, which makes the game unplayable. That happens even in fullscreen. I experienced that in Minetest and Open Arena. Btw the Open Arena view looks misplaced.

**Comment by ifreund** [comment]
This is likely due to river not yet implementing the `pointer-constraints-v1` and `relative-pointer-v1` protocols.

**Comment by minego** [comment]
Is this the cause of some applications (notably steam) not handling mouse input at all as well?

**Comment by ifreund** [comment]
> Is this the cause of some applications (notably steam) not handling mouse input at all as well?

Can't say for sure but this wouldn't surprise me. The main users of these protocols are (xwayland) games.

**Comment by ifreund** [comment]
Done in 26b0acddb7c56311b9d476c059d1e9af9d27dfbf
