### ISSUE TITLE
How to start programs with River

### ISSUE THREAD

**Issue by dedguy21** [ifreund/river#203]
In Sway, we can write into the configs which programs can start along with Sway startup. I'm wondering how we accomplish this in River.

I'd like to have my .azotebg started with River

**Comment by Ordoviz** [comment]
The default config file is a shell script so you can use arbitrary shell commands, e.g.:

```sh
mako &
/path/to/azotebg &
```

The `&` puts the program in the background.

**Comment by FoundOne** [comment]
You can make a copy of /etc/river/init to script in your ~/.config/river/init and add `riverctl spawn [your program]` in it.

**Comment by dedguy21** [comment]
Thanks

**Comment by dedguy21** [comment]
Keeping it closed, but how would I map the command 

wofi --show drun 

To my hot key
