### ISSUE TITLE
External Monitor Settings

### ISSUE THREAD

**Issue by dedguy21** [ifreund/river#204]
I have two external monitors, one is landscape and one in portrait. Also, each has a different refresh rate. I have kanshi, and have created profiles, however, my profiles are not recognized in River. 

How does one provide monitor settings to River?

**Comment by ifreund** [comment]
I've successfully used [wlr-randr](https://github.com/emersion/wlr-randr) and [wdisplays](https://github.com/cyclopsian/wdisplays) to configure river. I haven't personally tested kanshi but don't see a reason why that wouldn't work as well.

**Comment by dedguy21** [comment]
is there a command in River similar to swaymsg, that provides the current monitor settings status?

**Comment by dedguy21** [comment]
and actually because I'm slow, what command do we use to set the monitor settings in the init (config) file?  Sorry, I didn't seem to find that in the man pages in river-layout or river. Either that or I really need to go back to school and learn to read.

**Comment by Leon-Plickat** [comment]
> what command do we use to set the monitor settings in the init (config) file?

Whatever you'd use in your shell. The example init file is a shell script.

**Comment by dedguy21** [comment]
Yes, it's finally sunk in. Duh...
