### ISSUE TITLE
Arch Linux river-git r522.c143864-1:   border-color not changing

### ISSUE THREAD

**Issue by dedguy21** [ifreund/river#205]
using the following command in the init file does not change border colors

```
# Set border colors
riverctl border-color-focused #ffda00
riverctl border-color-unfocused #4f4f4f
riverctl border-width pixels 3
```

**Comment by Leon-Plickat** [comment]
The example init file, which you probably copied, is just a shell script. `#` is a comment in shell, so the colour code is never part of the command. Try quoting it.

**Comment by dedguy21** [comment]
Now I feel really stupid. Thanks that was the issue....
