### ISSUE TITLE
The applications do not respect the cursor theme

### ISSUE THREAD

**Issue by FoundOne** [ifreund/river#211]
`riverctl xcursor-theme [theme]` only works for the compositor itself. Most other apps just start using the cursor theme only by setting XCURSOR_THEME variable, but some apps like firefox or any electron app try to use their own cursor theme and I have no idea how to change that. Is there a way to fix that?

**Comment by Leon-Plickat** [comment]
For GTK things: 
```sh
gsettings set org.gnome.desktop.interface cursor-theme '$cursor_theme'
```

**Comment by FoundOne** [comment]
Thanks. GTK can be really annoying sometimes.

**Comment by ifreund** [comment]
> Note that there probably isn't really anything river can do about this: Wayland applications are responsible for drawing the cursor and (at least to my knowledge) have no way of asking the server to do it for them. How applications decide which theme to use differs a lot.

Pretty much, I don't think there's anything river can improve on with regard to this.

**Comment by dkwo** [comment]
This is mostly a GTK problem though, while QT do respect the cursor.
See also https://github.com/swaywm/sway/wiki/GTK-3-settings-on-Wayland and the wlroots issue there,
where it seems gtk devs prefer dbus as a solution (totally unacceptable).
Both for cursor and titlebar, gtk support for wayland is quite deficient at this stage.

**Comment by Leon-Plickat** [comment]
On Fri Mar 18, 2022 at 7:38 PM CET, dkwo wrote:
> This is mostly a GTK problem though, while QT do respect the cursor.
> See also https://github.com/swaywm/sway/wiki/GTK-3-settings-on-Wayland
> and the wlroots issue there,
> where it seems gtk devs prefer dbus as a solution (totally
> unacceptable).
> Both for cursor and titlebar, gtk support for wayland is quite deficient
> at this stage.

I mean, sure they don't exactly do what /we/ would like them to do,
but calling GTKs Wayland support "deficient" is dishonest and not
productive. Its developers just chose a different design paradigm than
we'd like. On their own platform it works fine and with a few minor
work-arounds it works on ours as well.

There are certainly a lot of things to improve regarding
interoperability of GNOME related software and critiquing their design
decisionsis fine (I do that too), but ranting is not.
