### ISSUE TITLE
[Feature Request] Riverctl Command to Unbind All Keybindings

### ISSUE THREAD

**Issue by BenEvolent333** [ifreund/river#213]
I think something like `riverctl unmap normal *` would be beneficial, in order to be able to reload keybindings without having to restart river or entering a bunch of `riverctl unmap` commands.

**Comment by Leon-Plickat** [comment]
What's the usecase for reloading keybindings? If you want different binds at some arbitrary time after startup, why not use modes?

**Comment by ifreund** [comment]
I think changing the behavior of `riverctl map` to overwrite existing bindings might be a better solution

**Comment by BenEvolent333** [comment]
That would work too. As someone who changes my keybindings a lot, it's helpful to be able to change the default keybindings on the fly. So when I edit them, I don't have to exit and restart river, I can just hit a keybinding to change them over.

**Comment by ifreund** [comment]
map/map-pointer now overwrite existing mappings: 5c0be25142a7c568e144257e5638343e327bef46
