### ISSUE TITLE
Replace river-status with river-options

### ISSUE THREAD

**Issue by Leon-Plickat** [ifreund/river#215]
We could potentially completely replace river-status with river-options, if we add per-seat options.

For example, each seat could have an options for the title of the focused view, each output could have options for the active and occupied tags, etc...

We'd need to ensure these options can't be changed by clients though.

**Comment by ifreund** [comment]
I don't think it makes sense to have options that can't be changed by clients tbh, that feels like an abuse of the options protocol.

**Comment by ifreund** [comment]
river-options has been removed
