### ISSUE TITLE
Some floating windows are not displayed when they are floating

### ISSUE THREAD

**Issue by snakedye** [ifreund/river#220]
Windows like swappy and imv disappear on my output when I launch them.

**Comment by YerinAlexey** [comment]
Do you have a multi-monitor setup? I couldn't reproduce this issue on the latest version

**Comment by ifreund** [comment]
Does fb7d50a019a8fccb0576189ff60e80436e760aa3 fix this?

**Comment by snakedye** [comment]
I do have a multi-monitor and the issues is fixed for imv but not [swappy](https://github.com/jtheoof/swappy).

**Comment by snakedye** [comment]
This could help.

https://user-images.githubusercontent.com/49378990/109357455-3c574080-7850-11eb-87f4-7db4d9094a14.mp4

**Comment by snakedye** [comment]
I'm noticing that this doesn't occur with server side decorations. Only when csd is enabled for an app.

**Comment by ifreund** [comment]
I can't reproduce this with swappy and `riverctl csd-filter-add swappy`. Can you still reproduce this issue? any other information that might be useful?

**Comment by snakedye** [comment]
The issue seems to be gone

**Comment by Leon-Plickat** [comment]
I can reproduce (or found a similar bug) where certain windows will not be displayed when they are floating via the float filter until resized.

Happens with this: https://git.sr.ht/~leon_plickat/snayk

**Comment by ifreund** [comment]
Should be fixed by e90474657fd83ef55575154cb3d0ff103249ccad
