### ISSUE TITLE
The taskbar module for waybar is only updated once I move windows to the output its on.

### ISSUE THREAD

**Issue by snakedye** [ifreund/river#225]
I have waybar on HDMI-A-1. Waybar's taskbar module only acknowledges a window exists once I move it from my second (DP-2) monitor to my first (HDMI-A-1).

For example, I spawn foot on DP-2, nothing shows up on Waybar, I spawn foot on HDMI-A-1, nothing shows up. I move foot from DP-2 to HDMI-A-1, foot appears on Waybar.

**Comment by ifreund** [comment]
Is this fixed by 3d66cbd2d4f58cf7c8953f6746b25b1731f4e80e?

**Comment by snakedye** [comment]
Yes, thank you

**Comment by ahmadraniri1994** [comment]
Would you mind to share your waybar config? 
Thanks.
