### ISSUE TITLE
htop in a foot terminal makes river to segfault on exit

### ISSUE THREAD

**Issue by FoundOne** [ifreund/river#235]
How to reproduce:

1. Start river
2. Start a foot server with `foot -s` and open a new foot client with `footclient` (it will probably work with several foot instances but I never tested it)
3. Run htop in it
4. Open a new foot client instance
5. Exit the river compositor (Super+E)

What happens: River segfaults and sometimes everything freezes and I have to restart the OS.

Here is the [log](https://gist.github.com/FoundOne/0a21e04901f2d165a49eec23b0773c69)

My platform characteristics are Manjaro-arm unstable aarch64 RK3399 (Pinebook Pro) river-git r565.27cac16-1 foot-git 1.6.4.r596.g098bc27-1

**Comment by ifreund** [comment]
I haven't been able to reproduce this. If you could get a stack trace with gdb it would likely be very helpful. You might also get more information in that log with a debug build of river.

**Comment by FoundOne** [comment]
After the simple damage tracking implementation, this no longer happens.
