### ISSUE TITLE
Alacritty can't find customized config in river

### ISSUE THREAD

**Issue by glyh** [ifreund/river#241]
I'm running river within X11, when I bind a shortcut key for spawning alacritty, it pop up and says there's no default config.

However, when I run a new alacritty instance in the old one, it turns out the config has been read succesfully.

 I wonder if there are some bugs in the spawn command, like not have the environment variables attached.

**Comment by ifreund** [comment]
> I wonder if there are some bugs in the spawn command, like not have the environment variables attached.

You can inspect the environment that alacritty is started in by river by running for example:
```
riverctl spawn "env > /tmp/foobar.txt"
```
I don't see anything amiss here though, I suspect an alacritty bug.

**Comment by glyh** [comment]
This problem has disappear automatically and I can't reproduce it. So I'm closing it.
