### ISSUE TITLE
HiDPI Support

### ISSUE THREAD

**Issue by glyh** [ifreund/river#242]
I'm trying river on my laptop, however I can't find a way to change the DPI, which results in everything on my laptop seems to small. Can you tell me how to change DPI in river wm?

**Comment by ifreund** [comment]
Use a `wlr-output-management` client such as `wlr-randr`, `wdisplays`, `kanshi`, etc. Also, questions like these are better suited to the IRC channel (#river on freenode) than the issue tracker.
