### ISSUE TITLE
Can't quit fullscreen when the layout manager isn't running

### ISSUE THREAD

**Issue by snakedye** [ifreund/river#243]
Linked to [this](https://github.com/ifreund/river/pull/112) PR on the river-layout-unstable-v1 branch

**Comment by Leon-Plickat** [comment]
You can exit fullscreen, the window will just have the same dimensions as it had in fullscreen (minus borders) and will be positioned at 0,0.

I'll fix it as soon as I find some time.

**Comment by Leon-Plickat** [comment]
@snakedye I pushed an experimental fix to the layout PR. I am not totally confident about it yet, but it does fix this issue.
