### ISSUE TITLE
The floating windows should always be displayed on top of tiled windows.

### ISSUE THREAD

**Issue by snakedye** [ifreund/river#244]
This issue is a compound result of multiple others. First, `focus disabled` doesn't work when I click on a window on another output so i have to use `focus normal` which makes it incredibly annoying to click on floating windows. It also doesn't make sense to have windows floating behind the tiled one because you usually make a window floating to better focus on it or have more manual control over its geometry.

**Comment by Leon-Plickat** [comment]
Unlike in sway, river does not have a second list of windows for the floating ones. There really is nothing special about floating windows, it is just a state and all it means is that the windows dimensions are not controlled by the layout generator. Other than that, "floating" has no meaning, nothing that would indicate them being displayed over tiled windows.

And I personally find that quite practical, tbh.

**Comment by snakedye** [comment]
Then making `focus disable` focus windows on other output a good compromise since I think the current behavior is not really what it is intended to be. The floating behavior is especially exacerbated by `focus normal`.

A good example of this is when you have a save pop up but your cursor is not within the bounds of the window so you have to drag your mouse but then you accidentally focus on the wrong window so have to go where you think the pop up is then focus the pop up using your keyboard and then make sure while you're clicking on it that the window behind doesn't grab your focus because you moved your cursor a bit too much on the left.

**Comment by snakedye** [comment]
Solved by https://github.com/ifreund/river/pull/277
