### ISSUE TITLE
Build unexpectedly terminated, exit code 11.

### ISSUE THREAD

**Issue by ahmadraniri1994** [ifreund/river#247]
I tried to build river on my machine (I use devuan and archlinux32), both of them are 32 bit and shared a same error "build unexpectedly terminated, exit code 11". Dependency is satisfied, I use zig binary (0.7.1). Any advice?

**Comment by ifreund** [comment]
Is that the full output produced by the build? If not could you pleas paste the complete output?

**Comment by ahmadraniri1994** [comment]
I am sorry for the delay... Here the full output. 
[river-build-log.txt](https://github.com/ifreund/river/files/6217151/river-build-log.txt)

**Comment by ifreund** [comment]
This seems to be an upstream issue with zig, you could open an issue here if you like: <https://github.com/ziglang/zig/issues>, I unfortunately don't have any 32 bit hardware to try myself.
