### ISSUE TITLE
Natural Scrolling

### ISSUE THREAD

**Issue by ElPresidentePoole** [ifreund/river#250]
Hello, it appears that there is no way to enable natural scrolling in river.  I'm coming from dwm with natural scrolling enabled in Xorg.conf.  Unless I am mistaken, there doesn't seem to be anything in riverctl to change the scroll behavior.

**Comment by ifreund** [comment]
Closing as a duplicate of  #71. You may be interested in [libinput-config](https://gitlab.com/kirbykevinson/libinput-config) as a workaround until this is implemented.
