### ISSUE TITLE
Can not build river on Arch

### ISSUE THREAD

**Issue by TheFineBroccoli** [ifreund/river#252]
I do have all of the dependencies installed, I did apply the workaround from issue #232 and I still can not build it.

[Here](https://pastebin.com/7UUSN9kQ) is the output of `zig build -Drelease-safe -Dxwayland --prefix /usr install`

**Comment by novakne** [comment]
try `sudo zig build -Drelease-safe -Dxwayland --prefix /usr install`

**Comment by TheFineBroccoli** [comment]
Not gonna lie, I felt really dumb for a moment there. But this just returns more zig (I assume) related errors ([here](https://pastebin.com/B3tkXemL))

**Comment by novakne** [comment]
hmm it looks like it can't find libc, can you share your `build.zig` please?

**Comment by TheFineBroccoli** [comment]
Yea that was it, I totally skipped over the word "append" in the comment of issue 232
