### ISSUE TITLE
Support for multiple keyboard layouts

### ISSUE THREAD

**Issue by YerinAlexey** [ifreund/river#254]
It's weird that nobody seems to care about multilingual input in river. I use river as my daily driver now and the only thing missing is this.

I would happily take the implementation but I don't really know how this should be done and sway code is a bit hard to read. ~~Hoping `#sway-devel` helps~~

**Comment by FoundOne** [comment]
I use the XKB environment variables to set my layout, but I can't have a proper layout indicator, which is the only issue I have when I switch layouts.

**Comment by YerinAlexey** [comment]
> I use the XKB environment variables to set my layout, but I can't have a proper layout indicator, which is the only issue I have when I switch layouts.

But I can't switch `XKB_DEFAULT_LAYOUT` at runtime, I need to relaunch river. Which _is_ the problem.

**Comment by YerinAlexey** [comment]
Turns out `XKB_DEFAULT_LAYOUT` supports comma separated layouts

**Comment by pystub** [comment]
How does one switch between layouts once your `XKB_DEFAULT_LAYOUT` is a list? Looked at the source, wlroots as well, but only found "magic" for VT switching, no mapping or commands concerning layouts.

**Comment by YerinAlexey** [comment]
> How does one switch between layouts once your `XKB_DEFAULT_LAYOUT` is a list? Looked at the source, wlroots as well, but only found "magic" for VT switching, no mapping or commands concerning layouts.

`XKB_DEFAULT_OPTIONS=grp:alt_shift_toggle` to switch with Alt+Shift. And `XKB_DEFAULT_OPTIONS=grp:ctrl_shift_toggle` to do this with Ctrl+Shift (if I remember correctly.)
