### ISSUE TITLE
Moving/Resizing views with high polling rate mouse doesn't work properly

### ISSUE THREAD

**Issue by Bonicgamer** [ifreund/river#255]
I recently got a new mouse and the first thing I noticed is that moving views around the screen felt weird, kinda like it didn't want to move sometimes.

I believe this is because River converts delta_x and delta_y into ints to move the view and then moves the cursor based on the difference in the current and pending positions of the view.

This can also be replicated by moving your mouse really slowly.

**Comment by ifreund** [comment]
I don't have a high dpi mouse and am unable to reproduce this by moving views slowly with my 3€ mouse. Views can't move less than a pixel, but moving my mouse slowly moves them one pixel at a time as expected.

**Comment by Leon-Plickat** [comment]
What is the DPI of your mouse?

My trackball has a DPI of 400. I am not sure if that is considered high, but I implemented moving and resizing everything worked fine with it and it still does.

**Comment by Leon-Plickat** [comment]
Ok I had a mouse lying around that supposedly has 4000 DPI. That one works fine as well. (I am not exactly sure if that thing is configures to use 4000, these things are now programmable after all, but I usually do not play around with such things).

Resizing is a bit choppy, but that is not because of the mouse DPI, but rather because the window you are resizing undergoes quite a lot of configure procedures. We might want to work on that a bit (perhaps buffer resize deltas for 0.2 seconds or something like that), but it is nothing major.

**Comment by Bonicgamer** [comment]
I just realized it probably doesn't have to do with a high DPI.

Report rate I believe is the real problem, which I have set to 1000 Hz according to Piper.

Anyways, if delta_? is < 1 and > -1 then the mouse and view move 0, and when that happens multiple times in a row, nothing will move because it never adds up to anything.

**Comment by Leon-Plickat** [comment]
Can you check if this issue persists in sway?

**Comment by Bonicgamer** [comment]
In Sway moving and resizing works smoothly no matter how I move my mouse.

**Comment by Leon-Plickat** [comment]
So I got hold of a windows computer to install that shitty software for the mouse to set it to 4000 DPI and 1000 Hz. Works fine, I wouldn't exactly call is *usable*, because 4000 DPI is outright masochistic, but river does what it is supposed to do on my laptop.

**Comment by Bonicgamer** [comment]
@Leon-Plickat Try a DPI of 100 with 1000 Hz.
For me the view doesn't move at all moving the mouse at a normal pace, which would mean that its a low DPI and high Report Rate problem, which means I'm dumb.

**Comment by Leon-Plickat** [comment]
I have no input device that supports both such a low DPI and such a high refresh rate.

**Comment by ifreund** [comment]
> For me the view doesn't move at all moving the mouse at a normal pace, which would mean that its a low DPI and high Report Rate problem, which means I'm dumb.

@Bonicgamer does this mean that this issue can be closed?

**Comment by Bonicgamer** [comment]
> @Bonicgamer does this mean that this issue can be closed?

I guess and then I can make a new issue, or should I rename this issue to "Moving/Resizing views with high polling rate mouse doesn't work properly"?
Sorry if that's a stupid question, I'm not good at this.

**Comment by ifreund** [comment]
So this is an issue with river and not with your funky mouse? :P 

Yeah we should just keep this open and correct the title then.

**Comment by zjeffer** [comment]
I think I have the same issue. I have a Logitech G502 and with the report rate set to 1000Hz (at 2400DPI), moving and resizing windows is incredibly sluggish, as if it's being held back by something. It also seems like it wants to lock onto the x and y axes while moving or resizing.

Setting it to 500Hz in Piper fixes this, but that's not ideal.

**Comment by ifreund** [comment]
I think that #459 should fix this, but I am unable to reproduce this issue on my hardware. If anyone who can reproduce this issue could test that PR it would be much appreciated!
