### ISSUE TITLE
Cursor Size Inconsistent

### ISSUE THREAD

**Issue by ElPresidentePoole** [ifreund/river#257]
![](https://i.imgur.com/F3sZuL9.png)

Hovering over wallpaper.

![](https://i.imgur.com/FK1Ogl7.png)

Hovering over Waybar.

I am new to wayland compositors and river, and I am aware that wayland clients can set their own cursor theme, but I can't figure out what is causing this.  I have

`riverctl xcursor-theme Adwaita`

in my river init script,

`gtk-cursor-theme-name=Adwaita
gtk-cursor-theme-size=24
`

in my gtk-3.0/settings.ini, and

`
gtk-cursor-theme-name="Adwaita"
gtk-cursor-theme-size=24
`

in my .gtkrc-2.0 file

I don't believe Waybar has a cursor configuration entry, as I couldn't find one while looking into this issue, so I'm not sure what else could be causing it.

**Comment by AtifChy** [comment]
run this ```gsettings set org.gnome.desktop.interface cursor-theme 'Adwaita'```

**Comment by ifreund** [comment]
This is an issue with whatever client you are hovering over or your configuration thereof, not with river. The gsettings config option AtifChy mentioned might fix this, I'm not sure and try to avoid the complexity of gtk stuff as much as possible myself.
