### ISSUE TITLE
null pointer deference with libxkbcommon and libxkbcommon-x11 1.2.0-1

### ISSUE THREAD

**Issue by novakne** [ifreund/river#258]
Needed to downgrade to  1.1.0-2 to fix it

[river log](https://paste.sr.ht/~novakane/8c8dd0ef74d82b07c6d96ee42635bce1723556da)
[gdb](https://paste.sr.ht/~novakane/2f891d581cd6286e141a805de4529b70c576a9b4)

**Comment by jaafarhatesgh** [comment]
I'm having a similar issue, I run `doas zig build -Drelease-safe --prefix /usr/local install`, then I get this [big ol' pile of errors](https://termbin.com/b049).

**Comment by ifreund** [comment]
> I'm having a similar issue, I run `doas zig build -Drelease-safe --prefix /usr/local install`, then I get this [big ol' pile of errors](https://termbin.com/b049).

This is unrelated, you get these errors because you are using wlroots 0.12.0 while river requires 0.13.0

**Comment by jaafarhatesgh** [comment]
Alright, I've opted in for `aur/wlroots-git` over the regular one, and it seems to fix the errors from the top. However, the errors from the bottom (starting with `ld.lld: error: /lib64/libxkbcommon.so: undefined reference to stat64@GLIBC_2.33 [--no-allow-shlib-undefined]`) still show up regardless of the `wlroots` version, what's causing that? I absolutely do have `libxkbcommon` installed. Both of which are at version `1.2.0-2`. Is that outdated as well?

**Comment by ifreund** [comment]
> Alright, I've opted in for `aur/wlroots-git` over the regular one, and it seems to fix the errors from the top. However, the errors from the bottom (starting with `ld.lld: error: /lib64/libxkbcommon.so: undefined reference to stat64@GLIBC_2.33 [--no-allow-shlib-undefined]`) still show up regardless of the `wlroots` version, what's causing that? I absolutely do have `libxkbcommon` installed. Both of which are at version `1.2.0-2`. Is that outdated as well?

See https://github.com/ifreund/river/issues/232

**Comment by jaafarhatesgh** [comment]
Thank you, it works! It was hard to find the other 2 calls to `linkLibC()` at first, though. My idiot brain realized I had to `grep` `.linkLibC()`, *not* `riverctl.linkLibC()`.

**Comment by novakne** [comment]
It was a problem in my init script and a libxkbcommon bug, see https://github.com/xkbcommon/libxkbcommon/issues/237
