### ISSUE TITLE
The new changes in the river AUR PKGBUILD script made it just x86_64 specific

### ISSUE THREAD

**Issue by FoundOne** [ifreund/river#259]
The new changes made the AUR package totally x86_64 specific. It was working out of the box before, if you ignore the architecture list (which some meta package managers like paru allow you to do). I'm even using the old version on my ARM computer and it works great, if you don't count one one glitch which I'm too busy (or too lazy) to investigate, which can easily be circumvented if you just close htop on exit. Also I hope the Arch maintainers add wlroots 0.13, because that's also an issue.

**Comment by ifreund** [comment]
Issues specific to the AUR package belong on the AUR, no packaging is maintained here.
