### ISSUE TITLE
[Idea] Enhanced monocle mode

### ISSUE THREAD

**Issue by lazy-dolphin** [ifreund/river#26]
##### Motivation

It becomes slow and tedious to switch between windows in traditional monocle mode when a large amount of windows is present in a tag or collection of tags.
##### How does this mode work?

A command `toggle_enhanced_monocle` is bound to `mod+M`. Say, the layout before pressing the key combination is `X`.
- When `mod+M` is pressed AND when the `mod` key which was held down for this press is released, currently focused window `W1` becomes fullscreen.
- Now, if the `mod` key is held down, windows are displayed in layout `X` again with window `W1` in focus and all windows at the same positions as before `W1` became fullscreen.
- Using the default keybindings `mod+j` and `mod+k`, we can change the focused window to, say, window `W2`.
- Now, when the `mod` key is released, the currently focused window `W2` becomes fullscreen.
- Holding down the `mod` key again, the windows are arranged in layout `X` again with window `W2` in focus and all windows at the same positions as before `W2` became fullscreen.
- When `mod+M` is pressed and the `mod` key is released, windows stay in layout `X`.

Note that enhanced monocle is not a layout by itself and uses other layouts to function.
##### Proposal

Modify the code for `full` layout, adding this functionality or
Add it with a different name, keeping the `full` layout as it is.
##### Advantages
- The exact amount of keypresses needed from switching from one window to another in monocle mode are known when the `mod` key is pressed, facilitating switching between windows.
- The arrangement of windows in the stack can be changed easily without toggling off monocle mode.
- Code reuse.

**Comment by Leon-Plickat** [comment]
This can not be implemented in river directly, as it will loose all layouts in the near future.

Instead, this could be done with keybinds, if it were possible to 1) bind commands to modifier keys and 2) bind commands to key releases and 3) query the currently active layout with `riverctl`.

**Comment by ifreund** [comment]
I think 2) and 3) are things that we definitely want to support eventually. I'm less sure about the benefits of 1). The described behavior seems fairly complex and I don't think it fits with what we want to ship with river. That being said, it should ideally be possible to use the tools river provides to implement something like this as a user.

**Comment by lazy-dolphin** [comment]
One possible use case of 1) would be mapping useless `CAPS LOCK` to commands.

**Comment by ifreund** [comment]
>One possible use case of 1) would be mapping useless CAPS LOCK to commands.

This can also be done on the XKB level, for example I have my capslock key remapped to escape by setting `XKB_DEFAULT_OPTIONS="caps:escape"`

**Comment by lazy-dolphin** [comment]
This can also be done on the XKB level, for example I have my capslock key remapped to escape by setting `XKB_DEFAULT_OPTIONS="caps:escape"`

Rebinding can be done but I don't think mapping `CAPS LOCK` directly to shell commands is possible using this method.

**Comment by ifreund** [comment]
> Rebinding can be done but I don't think mapping `CAPS LOCK` directly to shell commands is possible using this method.

Sure it is, remap the physical capslock key to some non-modifier key that is otherwise unused and then bind that. 

I'm closing this as `-release` bindings have already been implemented and #140 adds an event relaying the currently active layout to clients. There's nothing actionable left here.

**Comment by zgb124** [comment]
> > Rebinding can be done but I don't think mapping `CAPS LOCK` directly to shell commands is possible using this method.
> 
> Sure it is, remap the physical capslock key to some non-modifier key that is otherwise unused and then bind that.
> 

Sorry for commenting in such an old thread, but would anyone be so kind as to spell this method out for me? If for example I wanted to bind Capslock to an unused key such as XF86Calculator.

I have googled and ChatGPT'd for a couple of hours and am not having any luck.

**Comment by ifreund** [comment]
One can define a custom xkb layout for example, here's a link that should get you started: https://xkbcommon.org/doc/current/xkb-intro.html

**Comment by zgb124** [comment]
> One can define a custom xkb layout for example, here's a link that should get you started: https://xkbcommon.org/doc/current/xkb-intro.html

Thank you, I managed to figure it out:

```
default partial hidden modifier_keys
xkb_symbols "basic" {
    include "us(basic)"
    key <CAPS> { [ XF86Calculator ] };
};
```
