### ISSUE TITLE
Consider adding release/tags

### ISSUE THREAD

**Issue by branwright1** [ifreund/river#261]
Sorry for bothering but I'm going to maintain river in nixos repo and releases/tags might be helpful for versioning and building by hydra because for now  it's just uses specified commit hash and it's a bit harder to maintain it this way, after adding releases/tags river will be build from tarball by just editing hash from time to time to update it to new version (for example like sway and wlroots) and skipping small changes like fixing typos etc.

If user wouldn't be satisfied with version in repo there is simple way to override version/commit which can be replaced with shell.nix in wiki page once river will be merged into nixpkgs-master/unstable channel.

**Comment by Leon-Plickat** [comment]
There are no tags because there are no releases yet. A release is planned, but depends on a few things, including #112, zig 0.8.0 and possibly a few others.

**Comment by branwright1** [comment]
Well, just someone in nixpkgs said to open request for tags or releases, it's not necessary right now, we fixed commit naming as `river: unstable <commit date>` instead of `river: version > new version`

**Comment by ifreund** [comment]
Closing as it is intentional that there is not yet a release.
