### ISSUE TITLE
Make `attach-mode` global instead of per-output

### ISSUE THREAD

**Issue by FollieHiyuki** [ifreund/river#269]
This adds the ability to set `attach-mode` globally.
1 more reason is all the other configurations are consistent everywhere, and only `attach-mode` has to rely on the focused output.

**Comment by snakedye** [comment]
I think this could also be useful for layout generator.

**Comment by ifreund** [comment]
The `river-options` protocol has been removed. I also question whether it is really desireable to have different `attach-mode` settings per output, perhaps we should just make it global

**Comment by FollieHiyuki** [comment]
I will opt for making it global only, since my workflow is simple. But I think having the ability to change `attach-mode` on the fly for individual monitors is somewhat useful for "advanced" and more flexible use cases sometimes.
