### ISSUE TITLE
gaps

### ISSUE THREAD

**Issue by jedugsem** [ifreund/river#278]
the functions for changing the gaps were removed were is the new spot to change them

**Comment by jedugsem** [comment]
found it  in some comment

**Comment by ifreund** [comment]
The `rivertile(1)` man page also documents this fwiw.

**Comment by ahmadraniri1994** [comment]
I tried with rivertile but no luck, I changed the value (e.g rivertile outer-padding 3, etc). Outer-padding & view padding are moved from riverctl to rivertile, right?

**Comment by ifreund** [comment]
> I tried with rivertile but no luck, I changed the value (e.g rivertile outer-padding 3, etc). Outer-padding & view padding are moved from riverctl to rivertile, right?

Rivertile takes arguments including `-outer-padding` and `-view-padding` when it is started. For example:
```
rivertile -outer-padding 3
```
