### ISSUE TITLE
riverctl generates unexpected layout when main_count is greater than the maximum amount of views

### ISSUE THREAD

**Issue by Leon-Plickat** [ifreund/river#290]
Main views will not use all available space.

Also max_amount smaller than 1 are not possible, not sure if that is intended behaviour though.

![IMG_20210515_130601_286](https://user-images.githubusercontent.com/49593314/118358712-60d5d580-b580-11eb-9c50-f987f96bc3bd.jpg)

**Comment by ifreund** [comment]
I think disallowing `main_count` less than 1 makes sense. The behavior when it is greater than the number of views is a bug though, we should store the larger value but clamp it when generating the layout.
