### ISSUE TITLE
Arch Linux Build Error

### ISSUE THREAD

**Issue by dedguy21** [ifreund/river#293]
Arch Linux, have all the dependencies installed, ran 'git submodule update --init' command

Getting the following build error still

'sudo zig build -Drelease-safe -Dxwayland --prefix ~/.local install' : 

ld.lld: error: /lib64/libxkbcommon.so: undefined reference to stat64@GLIBC_2.33 [--no-allow-shlib-undefined]
ld.lld: error: /lib64/libxkbcommon.so: undefined reference to fstat64@GLIBC_2.33 [--no-allow-shlib-undefined]
error: LLDReportedFailure
river...The following command exited with error code 1:
/usr/bin/zig build-exe /home/user/.git/river/river/main.zig --library c --library evdev --library wayland-server --library xkbcommon --library pixman-1 --library wlroots -cflags -std=c99 -- /home/user/.git/river/zig-cache/zig-wayland/xdg-shell-protocol.c -cflags -std=c99 -- /home/user/.git/river/zig-cache/zig-wayland/pointer-gestures-unstable-v1-protocol.c -cflags -std=c99 -- /home/user/.git/river/zig-cache/zig-wayland/xdg-output-unstable-v1-protocol.c -cflags -std=c99 -- /home/user/.git/river/zig-cache/zig-wayland/pointer-constraints-unstable-v1-protocol.c -cflags -std=c99 -- /home/user/.git/river/zig-cache/zig-wayland/river-control-unstable-v1-protocol.c -cflags -std=c99 -- /home/user/.git/river/zig-cache/zig-wayland/river-status-unstable-v1-protocol.c -cflags -std=c99 -- /home/user/.git/river/zig-cache/zig-wayland/river-layout-v2-protocol.c -cflags -std=c99 -- /home/user/.git/river/zig-cache/zig-wayland/wlr-layer-shell-unstable-v1-protocol.c -cflags -std=c99 -- /home/user/.git/river/zig-cache/zig-wayland/wlr-output-power-management-unstable-v1-protocol.c --pkg-begin build_options /home/user/.git/river/zig-cache/river_build_options.zig --pkg-end -OReleaseSafe --cache-dir /home/user/.git/river/zig-cache --global-cache-dir /root/.cache/zig --name river --pkg-begin wayland /home/user/.git/river/zig-cache/zig-wayland/wayland.zig --pkg-end --pkg-begin xkbcommon /home/user/.git/river/deps/zig-xkbcommon/src/xkbcommon.zig --pkg-end --pkg-begin pixman /home/user/.git/river/deps/zig-pixman/pixman.zig --pkg-end --pkg-begin wlroots /home/user/.git/river/deps/zig-wlroots/src/wlroots.zig --pkg-begin wayland /home/user/.git/river/zig-cache/zig-wayland/wayland.zig --pkg-end --pkg-begin xkbcommon /home/user/.git/river/deps/zig-xkbcommon/src/xkbcommon.zig --pkg-end --pkg-begin pixman /home/user/.git/river/deps/zig-pixman/pixman.zig --pkg-end --pkg-end -I /usr/include/libevdev-1.0 -I /usr/include/pixman-1 -I /usr/include/libdrm -I /usr/include/pixman-1 -I /usr/include/uuid --enable-cache 
error: the following build command failed with exit code 1:
/home/user/.git/river/zig-cache/o/d186fa37413a9f5048f4cddccd74d8d0/build /usr/bin/zig /home/user/.git/river /home/user/.git/river/zig-cache /root/.cache/zig -Drelease-safe -Dxwayland --prefix /home/user/.local install`

**Comment by ahmadraniri1994** [comment]
I use branch master and succesfully compiled, you need to edit the build.zig and make libc-paths file and attach that file into build.zig.

**Comment by dedguy21** [comment]
The AUR package builds. Not sure why I'm getting errors from the git repo.
