### ISSUE TITLE
tag specific layout values

### ISSUE THREAD

**Issue by jedugsem** [ifreund/river#294]

**Comment by jedugsem** [comment]
generelly it would be scriptable but i think there whould be a option needed to get these values from rivertile if mod-layout-value is wanted to work

**Comment by jedugsem** [comment]
generelly it would be scriptable but i think there whould be a option needed to get these values from rivertile if mod-layout-value is wanted to work

**Comment by jedugsem** [comment]
generelly it would be scriptable but i think there whould be a option needed to get these values from rivertile if mod-layout-value is wanted to work

**Comment by jedugsem** [comment]
generelly it would be scriptable but i think there whould be a option needed to get these values from rivertile if mod-layout-value is wanted to work

**Comment by ifreund** [comment]
I don't understand what is being proposed here. Could you clarify?

**Comment by jedugsem** [comment]
If the default ratio between master and stack is 0.6 I want to change it on one tag to 0.8 for example but I want the other tags to remain 0.6.

**Comment by jedugsem** [comment]
Don't really know how it could be handled if more tags then one are visible but then it could simply be the average values.

**Comment by jedugsem** [comment]
I also wanted to achieve the same for the master count

**Comment by ifreund** [comment]
This can already be done by writing your own layout generator as leon pointed out. I have no plans to support such a feature in rivertile as I find it too complex and not very useful.

**Comment by jedugsem** [comment]
K thanks for the fast reply and sry for asking for features very nice window manager. I will try my best to do myself
