### ISSUE TITLE
[Feature Request] keybings for workspace next and workspace previous.

### ISSUE THREAD

**Issue by ishan9299** [ifreund/river#297]
I personally find using mod+(number for workspace) inconvenient when I am on workspace 5 or 6. In sway I had made a script which allowed me to use binding mod+d/a to go to next and previous workspace respectively. 

The issue I had with river was that I couldn't figure out a way to get the current workspace number/ tag I am on. If that was possible then writing a script to replicate that behavior won't be an issue. Other solution would be that we can just have a simple command that we can use in the config.

**Comment by ifreund** [comment]
I don't think this feature makes sense given the fact that river has tags not workspaces and you can focus multiple tags at the same time.

**Comment by arendorff** [comment]
Still, I'd be nice to be able to switch to the next/previous tag in the list instead of having to press a number key to get there.

**Comment by Leon-Plickat** [comment]
It is possible using the river-status protocol to write a simple Wayland client that does this. No need to implement this in river itself.
