### ISSUE TITLE
xwayland: window flickering and crashes

### ISSUE THREAD

**Issue by HeavyRain266** [ifreund/river#300]
Hello! for some reason when xwayland windows are opened for longer time then they are starting to flicker then there is only background color instead of window content in random places. Just noticed that on discord, jetbrains clion, idea and google chrome.

**Comment by ifreund** [comment]
You mention crashes as well in the issue title, would you happen to have a backtrace from one of these crashes or steps to reproduce it?

**Comment by HeavyRain266** [comment]
Only info was just broken wayland pipe after crash and alacritty log, to reproduce I was just coding in clion/idea and reading docs in browser, then windows started to flicker, acting weird with background in random places then river jusr freeze for a second and crash with broken pipe info

**Comment by FollieHiyuki** [comment]
I notice this bug too. It happens on Sway and Wayfire as well, so I assume this is more or less wlroots bug. I couldnt get the trace for wayfire and river, but luckily have a piece from dbus log for sway:
```
/bin/sh: 1: [calBackendLoader]: not found
propsReply "Method \"GetAll\" with signature \"s\" on interface \"org.freedesktop.DBus.Properties\" doesn't exist\n"
nmReply "Method \"GetDevices\" with signature \"\" on interface \"org.freedesktop.NetworkManager\" doesn't exist\n"
"Object path cannot be empty"
(EE) failed to read Wayland events: Broken pipe
wl_display_dispatch: Broken pipe
00:32:36 WARNING: The Wayland connection broke. Did the Wayland compositor die?
Gdk-Message: 00:32:36.135: Error reading events from display: Broken pipe
/bin/xdg-open: 881: x-www-browser: not found
05:30:19.762 [ERROR] [wlr] [backend/drm/atomic.c:35] connector HDMI-A-1: Atomic commit failed (modeset): Invalid argument
00:00:01.109 [ERROR] [common/ipc-client.c:87] Unable to receive IPC response
00:00:01.111 [ERROR] [common/ipc-client.c:87] Unable to receive IPC response
CRITICAL: Cannot connect to DBus.

(firefox:23659): Gtk-WARNING **: 21:32:37.305: cannot open display: :0
/bin/xdg-open: 881: iceweasel: not found
/bin/xdg-open: 881: seamonkey: not found
/bin/xdg-open: 881: mozilla: not found
/bin/xdg-open: 881: epiphany: not found
/bin/xdg-open: 881: konqueror: not found
/bin/xdg-open: 881: chromium: not found
/bin/xdg-open: 881: chromium-browser: not found
/bin/xdg-open: 881: google-chrome: not found
/bin/xdg-open: 881: www-browser: not found
/bin/xdg-open: 881: links2: not found
/bin/xdg-open: 881: elinks: not found
/bin/xdg-open: 881: links: not found
00:00:00.000 [ERROR] [common/ipc-client.c:67] Unable to connect to /tmp/fish.follie/sway-ipc.1000.1714.sock
[W][000019842.347358][media-session.c:2184 core_error()] error id:0 seq:105339 res:-32 (Broken pipe): connection error
```

It crashes here when I let Element open for quite a long time, and clicked on a link.

**Comment by HeavyRain266** [comment]
Looks like last rendering commits fixed those problems except Java GUI programs like Jetbrains IDEs but it's just general problem with Java GUI and Wayland. Sometimes they are rendered as border from river/sway and background from IDE's theme without any content. 

I don't think we can do anything about it because Java's libs related to X11 are having hardcoded list of WMs and all modern ones aren't on this list and there is needed some hacking like changing wm name to LG3D, using tons of envrinment variables and X11 rules for windows.
