### ISSUE TITLE
request to be added in the official void repo

### ISSUE THREAD

**Issue by Relected** [ifreund/river#302]
hello, i was wondering if the dev could consider adding the wm in the official void linux repo for void users :)

**Comment by novakne** [comment]
Probably once river get an official release, and ifreund use void so when river 0.1.0 will be released, he'll probably makes a template

**Comment by Relected** [comment]
> Probably once river get an official release, and ifreund use void so when river 0.1.0 will be released, he'll probably makes a template

niiiiice :D
