### ISSUE TITLE
Howto cycle through windows and fullscreen by default?

### ISSUE THREAD

**Issue by tmpm697** [ifreund/river#308]
I'd have two things:

1. I can use ctrl-alt to cycle through window apps -- I often open terminal and firefox at fullscreen and want to have alt-tab to cycle between them.
2. When I start an app like foot terminal or firefox, they'll start in fullscreen by default (take all space of screen to display -- not fullscreen mode in firefox)

How can I do above things? Many thanks.

**Comment by Leon-Plickat** [comment]
1. rivers way of window switching is **exactly** like alt-tabbing on windows, with the difference that the default keybind is different, you can go in both directions (forward and backward through the window list) and that it is instant without an annoying animation. Currently river does not allow to change the focus when a window is fullscreened, but you can write a layout that makes windows use all available space and then cycle focus normally.

2. How window layout and dimensions are determined by your layout generator.

**Comment by tmpm697** [comment]
I really want to just start any apps in fullscreen and have alt-tab to switch focus between them (I often have small set of windows to switch)

But I don't have experience enough with zig to have new layout implementation rn. Is there a document how to write one with Zig?

**Comment by Leon-Plickat** [comment]
You don't need to know zig, any language with Wayland binds will work.

What you want to do is write a layout that places all windows at `0,0` and using the entire available width and height. Then rebind alt+tab to focus the next window: `riverctl map normal Mod1+Tab focus-view next`.

**Comment by snakedye** [comment]
@tmpm697 by default [mine](https://gitlab.com/snakedye/kile/-/tree/main) does exactly that.

**Comment by ifreund** [comment]
There is currently no plan to allow focusing the next/previous view while in fullscreen. Note that changing tag focus on the other hand is allowed. 

As pointed out above, the behavior you want can be obtained with a custom layout client.

**Comment by Isti115** [comment]
Even though this issue is closed, I thought that I'd leave a pair of simple commands here, that together achieve an acceptable workaround to switching between fullscreen windows:

```
riverctl map normal Super Tab spawn 'riverctl toggle-fullscreen; riverctl focus-view next; riverctl toggle-fullscreen'
riverctl map normal Super+Shift Tab spawn 'riverctl toggle-fullscreen; riverctl focus-view previous; riverctl toggle-fullscreen'
```

It's not a proper solution, but chaining the process of toggling fullscreen off, switching the window and toggling fullscreen back on into a simple keybinding is usable if someone doesn't want to swap the entire layout engine.

_(Note: On my multi-monitor setup this creates some visual glitching on the other displays while switching.)_
