### ISSUE TITLE
Incredible cursor lag when plays CPU intensive mkv file using mpv?

### ISSUE THREAD

**Issue by tmpm697** [ifreund/river#309]
System:
```
OS: archlinux up-to-date
Kernel: 5.10.43-1-lts
CPU: intel core i7 
GPU: intel hd 620
mpv version: 1:0.33.1-2
monitor: dell 2k
```

Steps:
1. start river
2. start mpv command from terminal `alacritty` with no config under ~/.config/mpv (default config) to play an mkv file with below info:
```
RELEASE SIZE..: 10.5 GiB
RUNTIME.......: 1 h 31 min
VIDEO CODEC...: HEVC
FRAMERATE.....: 23.976 (24000/1001) FPS
BITRATE.......: 15.1 Mb/s
RESOLUTION....: 3840x2160 (2160p)
AUDIO.........: 6 channels : AC-3 @ 640 kb/s
```

3. start firefox 89.0 (up-to-date) and open some tabs with some urls.
4. observe cursor lag when moving around (don't need step 3 but to put more intense to river)

no tearing happens when plays the video file.

I don't have this problem of cursor lag with Xorg, but noticeable under river or I believe also happens in other wayland implementations.

Thanks.

**Comment by Leon-Plickat** [comment]
When something needs lots of CPU time, there is less time for river. That is pretty normal.

As for why this does not happen with X: Either X has a pretty low nice-ness (try altering your rivers nice-ness with `renice`), or your mpv uses hardware acceleration on X but not on Wayland (should be in the log output when run from a terminal).

**Comment by tmpm697** [comment]
I tested mpv both on wayland and x11 with default config (no mpv folder under ~/.config).

I notice some lines with mpv under wayland:
```
[   0.041][v][vo/gpu] Probing for best GPU context.
[   0.041][v][vo/gpu/opengl] Initializing GPU context 'wayland'
[   0.041][v][vo/gpu/wayland] Registered for protocol wl_shm
[   0.041][v][vo/gpu/wayland] Registered for protocol wl_compositor
[   0.041][v][vo/gpu/wayland] Registered for protocol xdg_wm_base
[   0.041][v][vo/gpu/wayland] Registered for protocol zxdg_decoration_manager_v1
[   0.041][v][vo/gpu/wayland] Registered for protocol wl_seat
[   0.041][v][vo/gpu/wayland] Registered for protocol wl_data_device_manager
[   0.041][v][vo/gpu/wayland] Registered for protocol wl_output
[   0.041][v][vo/gpu/wayland] Compositor doesn't support the wp_presentation protocol!
[   0.041][v][vo/gpu/wayland] Enabling server decorations
[   0.041][v][vo/gpu/wayland] Compositor doesn't support the zwp_idle_inhibit_manager_v1 protocol!
[   0.098][v][vo/gpu/opengl] EGL_VERSION=1.5
```

Something mpv needs but wayland/river didn't provide:
```
[   0.041][v][vo/gpu/wayland] Compositor doesn't support the wp_presentation protocol!
[   0.041][v][vo/gpu/wayland] Compositor doesn't support the zwp_idle_inhibit_manager_v1 protocol!
```

How to fix this and is this can cause the issue?

**Comment by tmpm697** [comment]
I also observe lag when plays 1080p youtube video, so probably this issue related to wayland protocol or the implementation or GPU intel hd620.

**Comment by tmpm697** [comment]
I've tested on `sway` and `dwl`, `dwl` even worse and `sway` is better compare to `river`.

So `sway` must be implemented something that improve how its display pixels and de-stress cpu usage or else?

**Comment by tmpm697** [comment]
in `sway`, when you move mouse around mpv window, it has lag, but when focus/select terminal window, speed of mouse has no lag.

but in `dwl` and `river`, there're seem lag for all apps.

**Comment by ifreund** [comment]
> I've tested on `sway` and `dwl`, `dwl` even worse and `sway` is better compare to `river`.

Sounds like this is #206
