### ISSUE TITLE
Howto remap cap-lock to control?

### ISSUE THREAD

**Issue by tmpm697** [ifreund/river#310]
Gg and tried `hwdb` but can't have it work `https://unix.stackexchange.com/questions/571632/udev-keymapping`

Is there a way `river` supports to re-map cap-lock to control? So that I can use cap-lock as control (leftcontrol) with all other apps under `river`? (alacritty, firefox, foot, ..etc)

**Comment by tmpm697** [comment]
adding `export XKB_DEFAULT_OPTIONS=ctrl:nocaps` to .zshenv or start before `river` doesn't work.

I've set `export LC_TIME=ja_JP.UTF-8' if related.

**Comment by ifreund** [comment]
How are you starting river? Try running `XKB_DEFAULT_OPTIONS=ctrl:nocaps river` from a tty, it should work.
