### ISSUE TITLE
Add support for natural scrolling

### ISSUE THREAD

**Issue by mitinarseny** [ifreund/river#315]
Firstly, thanks for great work!

Could you add support for natural-scrolling configuration for libinput https://wayland.freedesktop.org/libinput/doc/latest/configuration.html#scrolling?

[Hikari](https://hikari.acmelabs.space) does have it

**Comment by novakne** [comment]
It is already implemented, look at the input configuration section of `man riverctl`

**Comment by mitinarseny** [comment]
Hey, thanks for the quick response! Yeah, I actually just looked through recent commits and found this. But as for now, there is a compilation error:
```sh
zig build -Drelease-safe --prefix /usr install
./river/InputConfig.zig:292:22: error: no member named 'getLibinputDevice' in struct '.wlroots.types.input_device.InputDevice'
        device.device.getLibinputDevice() orelse return,
```

**Comment by Leon-Plickat** [comment]
You need to update zig-wlroots, the binding for that function was only added a few days ago.

**Comment by mitinarseny** [comment]
Oh, sorry, totally forgot to update git modules.
Thank you! 

P.S.: I am a big fan of your work)
