### ISSUE TITLE
Package for Void Linux

### ISSUE THREAD

**Issue by mitinarseny** [ifreund/river#316]
Could you add river as a package for void linux?
It seems that you already use void for CI

**Comment by ifreund** [comment]
I use void linux and will package river for void when river `0.1.0` is released.

**Comment by mitinarseny** [comment]
@ifreund So, river [v0.1.0](https://github.com/riverwm/river/releases/tag/v0.1.0) has been released, but it is still no `river` package in their Void Linux repositories... I am very excited to be able to install and keep upgrading by using package manager, rather than recompiling every time I pull new commits from master!

**Comment by ifreund** [comment]
@mitinarseny see https://github.com/void-linux/void-packages/pull/29288
