### ISSUE TITLE
Add support for listing only inputs of a given type

### ISSUE THREAD

**Issue by mitinarseny** [ifreund/river#317]
At the moment, list of inputs with their types are available via `riverctl list-inputs` command.
It would be convenient for configuration scripts if there is a way to filter only inputs of given type.
For example, I would like to enable natural scrolling on all of my `pointer` inputs. 
```sh
for i in $(riverctl list-inputs --type pointer); do
  riverctl input $i natural-scroll enabled
done
```
Otherwise, it can be done with `sed` for now, but it does not seem like it is a right way to do it.

**Comment by Leon-Plickat** [comment]
The output of `riverctl list-inputs` is easily machine parseable. You can probably create a little awk script that just extracts the names of pointer devices. But you don't actually need that. You can configure a setting even for device that don't actually support it without any problem.

The proper way to do what you want to do here is to add a way to create input configs based on type. Sway can do that as well, for reference.

**Comment by ifreund** [comment]
Nack on any flag to make river perform filtering of the output of `list-inputs`. If there are small changes that can be made to make it easier to filter with standard unix utilities that would be fine by me, but I don't see any major issue with the status quo.

> The proper way to do what you want to do here is to add a way to create input configs based on type. Sway can do that as well, for reference.

This seems like it might be a UX improvement, but I'd rather not implement this yet as it's not yet clear to me what direction river's input configuration will take long-term. Therefore keeping things as simple as possible for now without sacrificing functionality even if it means extra verbosity in some cases means that we will be less likely to break things later on.
