### ISSUE TITLE
How to set wallpaper?

### ISSUE THREAD

**Issue by tmpm697** [ifreund/river#318]
I've tried to set wallpaper as below command before and after `river` comand:
```
swaybg -i <existing tested path to jpg image> -m fill
```
Both didn't set wallpaper and `river` keeps using default green one. How to set wallpaper in `river`?

**Comment by novakne** [comment]
Your command should works, either this or in your river init `riverctl spawn 'swaybg -i <path/to/image> -m fill'`, and that answer #319 too, if you want to start something at startup use `riverctl spawn <app>` in your river init.
e.g. `riverctl spawn alacritty`
