### ISSUE TITLE
Change default green wallpaper to another color?

### ISSUE THREAD

**Issue by tmpm697** [ifreund/river#321]
I tried:
```
riverctl background-color #RRGGBB
err: Error: not enough arguments
```
I got above error, I don't want to set wallpaper with `swaybg` but want to just change color of default wallpaper, howto?

**Comment by novakne** [comment]
Try with quote `riverctl background-color '#RRGGBB'`

**Comment by tmpm697** [comment]
@novakne I got the same error:
```
riverctl background-color '#RRGGBB'
err: Error: invalid character in argument
```

**Comment by novakne** [comment]
What color are you trying? The exact command you write?

**Comment by tmpm697** [comment]
I used this exact command ass mentioned above: `riverctl background-color '#RRGGBB'`

I want to set it black or red or any hex colors.

**Comment by novakne** [comment]
`#RRGGBB` is the color format you need to replace it with the actual hex color you want, e.g. `riverctl background-color '#ffffff'`
