### ISSUE TITLE
Turning off monitors sends all windows to one output

### ISSUE THREAD

**Issue by thallium** [ifreund/river#329]
I have two monitors, after I turn off both and then turn on, all the windows were sent to one monitor(output) and my screen scaling is also reset.

**Comment by Leon-Plickat** [comment]
> I have two monitors, after I turn off both and then turn on [...] screen scaling is also reset.

River does not store output configurations for outputs that do not / no longer exist. If hot-plugging outputs is something you do often, you can use [kanshi](https://github.com/emersion/kanshi), an output configuration daemon.

**Comment by thallium** [comment]
Is press the power button of monitor count as hot-plugging? What about the problem with windows?

**Comment by Leon-Plickat** [comment]
> Is press the power button of monitor count as hot-plugging?

Since river no longer sees the output, apparently yes.

>  What about the problem with windows?

When an output is destroyed and river moves its windows to another one, it does not keep track of on which output they were previously one. I wouldn't call it a "problem" per se, just an unsupported use case.

**Comment by thallium** [comment]
> When an output is destroyed and river moves its windows to another one
That's not what I experienced. Let me describe it in detail: when I turn off one monitor, nothing happened. After turning off both monitors, let's call my two monitor monitor A and monitor B, if I turn on A first, then B, all windows will appear on B. If I turn on B first, I'm simply logged out.

**Comment by ifreund** [comment]
> That's not what I experienced. Let me describe it in detail: when I turn off one monitor, nothing happened. After turning off both monitors, let's call my two monitor monitor A and monitor B, if I turn on A first, then B, all windows will appear on B. If I turn on B first, I'm simply logged out.

It sounds like there's probably a bug here based on that description. I'll be returning to my desktop setup with multiple monitors this weekend and will take a look.

**Comment by ifreund** [comment]
@thallium I am unable to reproduce this issue following those steps. What happens for me is the following:

1. unplug A  (all windows are moved to B)
2. unplug B
3. plug in B (all windows are on B)
4. plug in A (all windows still on B) 

or 

1. unplug A  (all windows are moved to B)
2. unplug B
3. plug in A (all windows are on A) 
4. plug in B (all windows still on A)

I'm never logged out, no matter what order I plug/unplug the monitors. 

For my monitors at least, using the power button is not the same as unplugging them. If I use the power button instead, no windows are moved at all.

**Comment by ifreund** [comment]
If anyone else is able to reproduce this and provide more detailed steps, feel free to leave a comment and I'll reopen.
