### ISSUE TITLE
Cursor only updates on pointer move.

### ISSUE THREAD

**Issue by Leon-Plickat** [ifreund/river#337]
How to reproduce:

1. Have a view on one tag which sets a cursor image.
2. Have a different view on a different tag which sets a cursor image.
3. Focus the first view, move mouse in center of it. The cursor should be the image set by this client.
4. Switch the tag focus, so that the other view is focused and under the cursor. The cursor image does not change.
5. Move the pointer. The cursor image will change now.

**Comment by ifreund** [comment]
Fixed by a3c657132674520de9f52de805057a598abfc5a2 and following commits.

**Comment by Leon-Plickat** [comment]
@ifreund actually one of your recent commits reintroduced the bug, probably 53dd387

**Comment by ifreund** [comment]
@Leon-Plickat Sorry bout that, re-fixed in f371e00716898d2330c22d2f17d9785e918f115e
