### ISSUE TITLE
Segmentation fault on x86_64-musl Void Linux

### ISSUE THREAD

**Issue by ReneganRonin** [ifreund/river#342]
river suddenly closes with segmentation fault:
`Segmentation fault:19.767: Error reading events from display: Broken pipergs 2 21523 140732251090181 11 1 29756.`
I am not entirely sure what causes the segfault. It can be unrelated to river

**Comment by Leon-Plickat** [comment]
The error message sounds more like something from a client than something river would emit. Probably just some program that can't handle the Wayland connection suddenly dying.

Your bug reports isn't clear on this: Did you exit river yourself and saw the segmentation fault or did it crash unexpectedly? In the latter case, please try to reproduce and post a log.

**Comment by ReneganRonin** [comment]
it crashed unexpectedly and then i saw that segfault message on the tty.

**Comment by ReneganRonin** [comment]
Oh lol. I just noticed the recent commit can only use wlroots 0.14.0. and the one in the void repo is 0.13.0. closing this issue as this is just an issue with versions of wlroots
