### ISSUE TITLE
Absolute resize and move commands and window specific options

### ISSUE THREAD

**Issue by jedugsem** [ifreund/river#343]
I think there should be a command to place a window on the screen exactly where you want to and with the size you want to. Maybe like sway it does but it whould reqire to pass in the app ID or something similar. Additionally I miss a self option and a app-id option for the set-view-tag command so that something like riverctl set-view-tags -id Firefox active-tag.

**Comment by Leon-Plickat** [comment]
> I think there should be a command to place a window on the screen exactly where you want to and with the size you want to. 

What is your use case?

> Maybe like sway it does but it whould reqire to pass in the app ID or something similar.
> [...]
> Additionally I miss a self option and a app-id option for the set-view-tag command so that something like riverctl set-view-tags -id Firefox active-tag.

App-ids are not the best way to identify windows, so including them in commands is not a particularly good idea IMO. Toplevel handles are better. And riverctl commands should probably just apply to the focused window.

But these kind of things are unlikely to be added before a river-control rewrite.

**Comment by jedugsem** [comment]
I used a terminal with nmtui to configure my network and in sway and awesomewm I let it be placed below my wifi indicator in my waybar/aswesomebar

**Comment by jedugsem** [comment]
I don't really know much about app Ids or other window identifier but I think it whould be very useful and comparable with the bspwm inspired scripting capablys. For example window swallowing can't be done with river features ATM because there no way to bring the window back from some junk tag expect such a function or with focusing this workspace and window .Generally for a scriptable window manager its really useful to use commands for specific windows. Thanks for the answer and i'll wait for the rewrite to look into it myself.

**Comment by Leon-Plickat** [comment]
> For example window swallowing can't be done with river features ATM [...]

Note that implementing swallowing this way is an incredibly ugly hack, as I have pointed out in a different issue before.

Instead, you could try to use cage.

> Generally for a scriptable window manager [...]

Also note that scriptability, specifically with scripting languages, is not the main goal of river. You can control river via external programs, but the approach river uses favours Wayland clients or just simply internal features over scripting. Mostly because Wayland extensions map very badly to shell scripting.

Also Waylands promise of "every frame is perfect" does not work at all with shell scripting.

**Comment by jedugsem** [comment]
thanks the cage thing didnt work last time but with the d option it works

**Comment by jedugsem** [comment]
But a few really annozing problems with cage are that i cant choose for which programms the terminal should swallow and i can only close the window for example mpv though its own keybinding and not my global keykombo

**Comment by ifreund** [comment]
This issue is a varied assortment of rather vague feature requests, none of which I currently intend to implement.
