### ISSUE TITLE
Caps lock => escape

### ISSUE THREAD

**Issue by nagy135** [ifreund/river#347]
I m new to wayland so I might be asking at wrong place, but how does one rebind capslock to escape on wayland?

On X it was `setxkbmap -option caps:escape` but it doesnt seem to work for me now. I ve been googling a bunch but I saw people are specifying some setting for SWAYWM to have this so it appears as "wm setting" instead of "general x server setting" as I thought about it until now.

Can someone help me with this one? Or educate me where should this feature be located at all

**Comment by novakne** [comment]
Probably with `export XKB_DEFAULT_OPTIONS=caps:escape` in your .profile, bash_porfile, zprofile or whatever shell you're using. I'm not 100% sure about the options since I don't use any but it should be something like this

**Comment by nagy135** [comment]
Silly of me, it is present in manpage as well but in my defense it wasnt that easy to find there. But yea that exactly works
