### ISSUE TITLE
Option to disable and enable outputs (monitors)

### ISSUE THREAD

**Issue by user18130814200115-2** [ifreund/river#348]
It would be really useful if you could add a function to riverctl so it can disable and enable outputs similarly to:
```
swaymsg "output $internal disable"
```
For clarity, in sway this turns the display fully black and moves all workspaces on it to the other display, though this latter part does not apply to river.

Edit:
PS.
Sorry if this is already an option that I have looked over, I have gone over the manpage multiple times.

**Comment by HeavyRain266** [comment]
It's not implemented but you may want to use [kanshi](https://sr.ht/~emersion/kanshi/) daemon to manage your monitors through e.g. loading different profiles/configs by keybindings in river.

**Comment by Leon-Plickat** [comment]
You can use wlr-randr to do this. This will probably not be added to riverctl since the functionality already exists in other clients.

**Comment by user18130814200115-2** [comment]
You are both right, It seems I have been spoiled by sway.
I partly assumed this needed to be implemented at the compositor level, though I knew these programs existed.

case closed
