### ISSUE TITLE
Building on NixOS

### ISSUE THREAD

**Issue by bryanhonof** [ifreund/river#35]
Hey,

First and foremost, cool project I love the approach you're taking!

Secondly, I tried building it on NixOS but had to add a bit more build dependencies than listed in the `README.md`.

This is my `default.nix`:
```nix
with import <nixpkgs> {};
stdenv.mkDerivation rec {
	name = "river";
	buildInputs = [
		pkgs.zig
		pkgs.wayland
		pkgs.wayland-protocols
		pkgs.wlroots
		pkgs.libxkbcommon
		pkgs.pkg-config
		pkgs.libudev
		pkgs.libGL
		pkgs.xorg.libX11
		pkgs.pixman
	];
}
```

Notably, the `pkgs.pkg-config`, `pkgs.libudev`, `pkgs.libGL`, `pkgs.xorg.libX11` and `pkgs.pixman` had to be added in order for it to build successfully.

I am leaving this here just in case other people are having the same problem as me on NixOS.

**Comment by ifreund** [comment]
Hey, thanks for letting me know! River does link `pixman` directly and uses `pkg-config` during the build process so I just added those to the list in the readme. I'm a little confused by the others though as they seem like dependencies of wlroots not river. However i have 0 experience with nix so perhaps I am missing something.

**Comment by bryanhonof** [comment]
No, I too think this is just something nix specific since I can create an isolated shell with only those packages. Just like you can create virtual environments with python.
So those extra packages are probably indeed dependencies of another package.

I just posted it so, when someone that also uses NixOS comes by, they'll know what to do.

**Comment by ifreund** [comment]
Cool, I think this kind of thing belongs in the wiki tbh, so I copied your nix snippet to a new page there and am going to go ahead and close this issue.  I made the wiki world-editable I believe, so feel free to expand on what I copied or add anything you like!
