### ISSUE TITLE
Dropdown Window

### ISSUE THREAD

**Issue by nagy135** [ifreund/river#355]
This [issue#322](https://github.com/ifreund/river/issues/322) looks like the closest one to "dropdown" (one key bind either hides/shows specific window or creates new instance if none exist). This is probably scriptable with cli tools, but I see 2 issues and I would like to ask if you can suggest any solutions.

1. Hide window - This is what [issue#322](https://github.com/ifreund/river/issues/322) is about and if i understood it correctly you are suggesting "changing tags". I would suggest there should be specific combination of tags that means "show nowhere" and have list/toggle commands for those. This could probably take form of **0 tags**, but i understand this would be problematic at this point. At this point all we can is *sacrifice one tag* as a hidden (i m thinking of unbinding 9th tag management and have it as "hidden one").

2. Resize window - I think most of us expect dropdown terminal to be floating one at some specific location and I dont see option to do that in riverctl. We have **resize** and **snap** but i dont see how would i use those to get to a desired geometry of, lets say, **200x200+860+440**. I used to do these in bspwm with xdotool, and i m not sure if thats what i should use here (do we rely on this because of xwayland?)

I rely on this feature, I always have 2 hidden windows in the middle of screen for fast shell access over whatever I currently do (also one with python shell as calculator). If some of you managed to implement this on wayland/river, please let me know !

**Comment by ifreund** [comment]
Without getting into details, have you see this wiki page? https://github.com/ifreund/river/wiki/Scratchpad

**Comment by novakne** [comment]
You could use a scratchpad as explained in the [wiki](https://github.com/ifreund/river/wiki/Scratchpad)

Personally my setup is mapping a key to a floating Foot instance 
```bash
riverctl float-filter-add "float"

term_float=(footclient --app-id 'float' --window-size-pixels 1200x800)
riverctl map normal ${mod}        T      spawn ${term_float[@]}
```
Then I just send this window to the scratchpad and toggle like in the wiki

**Comment by nagy135** [comment]
Hmm i apparently missed that one, nevertheless, it kinda still is *sacrifice* I described (even thou much smaller one).
One more thing to point out is you apparently set size on instance itself, and making river respect it. There are at least few of my personal app (and I m sure much more) that dont have any flag like that, so something more general would be nice (i would imagine *spawn* could have option for geometry)

Anyway, this works for me... so thanks.
