### ISSUE TITLE
river doesn't send a configure event when a surface needs to be resized

### ISSUE THREAD

**Issue by snakedye** [ifreund/river#356]
Demo

https://user-images.githubusercontent.com/49378990/125513069-ae8d5bbb-0af4-465c-b986-163ef68c0468.mp4

[paper.log](https://github.com/ifreund/river/files/6811449/paper.log)

**Comment by ifreund** [comment]
I can't reproduce this using a patched version of `swaybg` which doesn't set exclusive zone to -1 and waybar. What clients are you using here?

**Comment by snakedye** [comment]
the [client](https://gitlab.com/snakedye/paper.git).

**Comment by snakedye** [comment]
I am very confused this morning. Tested the same executable again and I am still experiencing the same issue. I'm pretty sure now the error isn't with river since swaybg is able to get a configure event.

I'll update this once I manage to solve the real issue.

**Comment by ifreund** [comment]
Testing your client on other compositors such as sway, wayfire or hikari might also be interesting.

**Comment by snakedye** [comment]
Setting the size of the layer surface to 0 did the job most likely because of this.

>If you pass 0 for either value, the compositor will assign it and inform you of the assignment in the configure event. You must set your anchor to opposite edges in the dimensions you omit; not doing so is a protocol error. Both values are 0 by default.
