### ISSUE TITLE
init Key Bind  example fails

### ISSUE THREAD

**Issue by plum** [ifreund/river#362]
Hi, River has an excellent  tiling scheme and I like it, just as I enjoyed dwm for a long time.

Starting out recently with Wayland only on Arch linux, latest linux-lts kernal, I launch River from TTY with the command, $River, as a single  TTY  session.

I am unable to get any custom key binds to work, following, and including the example given in the example init file:
`riverctl map normal Mod4 P spawn bemenu-run  
 `
Other attempts fail in response from Riverctl, such as ,
`riverctl map normal $mod N spawn /home/user/.scripts/rofi_notes.sh`

`riverctl map normal $mod N exec /home/user/.scripts/rofi_notes.sh`

The above is an example of a script that runs fine when launched within Alacritty at the prompt, as does bemenu-run.

However, when changing the default $mod key to Mod1 (i.e. Alt_L), and restarting River, the change is recognised, and I so I am able to launch alacritty with an 'Alt+Return' and any other default binding I care to use.

I am using the latest git version of River, r.658 installed from aur repository.

I would appreciate any help with this issue.

 I saw earlier that a similar issue had been raised, but didn't supply a solution, nor a reason as to why this fails, other than compatibility with other Wayland compositors, such as sway.

I do have sway on the computer, downloaded  for testing. I prefer River to i3, having found it since. 
I wonder does that mean I have a conflict just by it's presence as an installed package? I would have thought not.

Forgive my naivety, for  I am new to Wayland only sessions, and compositors.

As a sidenote, and perhaps it is relevant, I have also found similar non-responsiveness to custom key binds with the compositor Vivarium. 
With Sway, my custom key binds worked without any problem.

John

**Comment by HeavyRain266** [comment]
Is your init file executable? version from AUR is outdated and looks like unmaintained. You will have d to build river from master branch by hands.

**Comment by plum** [comment]
> Is your init file executable? 
Yes.
I'll install as suggested into /usr/local from source, and then try it out that way, as you suggest.

Thanks for your  kind and quick reply.

John

**Comment by plum** [comment]
Update on Further Testing:
----------------------------------

Having installed River from git master to /home/user/.local and using the installation's /etc/river/init, I find the problem with custom key binds persists on my system.

The single mapping as given by example in man riverctl,
`riverctl map normal $mod P bemenu-run`
fails to launch bemenu, whreas it does fine in the terminal. I have switched form alacritty to foot, as per  example init.

**Comment by novakne** [comment]
> The single mapping as given by example in man riverctl,
> `riverctl map normal $mod P bemenu-run`
> fails to launch bemenu, whereas it does without problems in the terminal.

You're missing `spawn` in your command `riverctl map normal $mod P spawn bemenu-run`

**Comment by plum** [comment]
> You're missing `spawn` in your command `riverctl map normal $mod P spawn bemenu-run`

Yes , well spotted.  Actually I have it in my init file, a silly mistake I made here in duplicating the command. Apologies to all.

This is what I have, and what fails as per opening post:

`riverctl map normal $mod P spawn bemenu-run`

**Comment by ifreund** [comment]
would you mind pasting your whole init file here? Are there any errors logged by river on startup?

**Comment by plum** [comment]
> would you mind pasting your whole init file here? Are there any errors logged by river on startup?

Not at all, thanks for the invitation.
here it is:

**Comment by plum** [comment]
Note: I  closed and then re-opened the issue in the last hour, because I had closed it by mistake, when pressing the wrong button, thinking I was closing a dialogue box.

**Comment by novakne** [comment]
In your init
```
## CUSTOM Key Binds
riverctl map normal $mod P exec bemenu-run
```
That's wrong, `riverctl map normal $mod P spawn bemenu-run`

Other than this, it looks like the default config and everything should works, I don't see any unusual errors in the log too

**Comment by andreafeletto** [comment]
> Is your init file executable? version from AUR is outdated and looks like unmaintained. You will have d to build river from master branch by hands.

I'm the maintainer of the river-git AUR package. The version you see in the aur page just refers to the latest version of the master branch coinciding with the last update of the PKGBUILD. This is true only for *-git packages of course.
`makepkg` will always clone or pull the latest commit and compute the right version before compilation and installation.
