### ISSUE TITLE
Fullscreen behaviour with web browser

### ISSUE THREAD

**Issue by nagy135** [ifreund/river#364]
Hi, I would like to clarify this different behaviour i see between some apps regarding their "app triggered fullscreen". Some apps behave different than others (i will give 2 examples).

## mpv
If i press `F` inside mpv it goes to fullscreen mode, basically the same thing that would happen if i used river's fullscreen. They both act exactly the same, one can revert the other. No issues here, this is how it should behave imho.

## chromium web player
On multiple websites I see different behaviour tho (examples youtube, netflix) if you press its fullscreen bind `F` window simply occupies its tile as if that was the size of your monitor. Then you need to press river's fullscreen to actually get there. Thats strange but it acts even worse on reverse. If you then cancel browser's fullscreen with `escape`, you get to this strange situation where [browser thinks it has smaller window but it doesnt](https://i.ibb.co/yYxsDdZ/20210716-06h40m34s-grim.png) (notice those black borders on top/right)

I understand this might be chromium issue where it doesnt update, but this didnt happen on X11 on bspwm, so I would just like to know where the difference is and maybe provide answer for others because this surely behaves annoying.

**Comment by ifreund** [comment]
Hmm, is your chromium running through xwayland? Firefox behaves perfectly for me, the river binding and firefox binding work the same.

**Comment by nagy135** [comment]
I m running [arch repo chromium](https://archlinux.org/packages/extra/x86_64/chromium/). I m pretty sure you are right (if it works for you), and this is some not updated feature flag. I will try to compile from source with it and if that wont work I will link issue to chromium github.

**Comment by ifreund** [comment]
To be clear I'm using firefox not chromium. I'm not up to speed on whether distros are shipping chrome with the wayland backend enabled by default yet or not. If your chromium is running wayland-native, I would expect this to work the same as mpv or firefox.

**Comment by HeavyRain266** [comment]
> To be clear I'm using firefox not chromium. I'm not up to speed on whether distros are shipping chrome with the wayland backend enabled by default yet or not. If your chromium is running wayland-native, I would expect this to work the same as mpv or firefox.

I've tried chrome/chromium with wayland backend and doesn't change anything, fullscreen mode still isn't fullscreen but just fill view container not whole screen unless you use `riverctl toogle-fullscreen` on those browsers. Looks like it's their own problem, first I was wandering it's Xwayland but looks like badly implemented fullscreen behaviour in browser itself.

**Comment by ifreund** [comment]
heh, if chromium doesn't send the `xdg_toplevel.set_fullscreen` request there's nothing river can do. If you use `WAYLAND_DEBUG=1` and see chromium sending this request but river doesn't respond, then there's probably a river bug.

**Comment by HeavyRain266** [comment]
> heh, if chromium doesn't send the `xdg_toplevel.set_fullscreen` request there's nothing river can do. If you use `WAYLAND_DEBUG=1` and see chromium sending this request but river doesn't respond, then there's probably a river bug.

Already tested and doesn't send any fullscreen related requests. I assume in this case best solution would be using different browser such as firefox or qutebrowser (which is also native through Qt backend and fullscreen works) or just sending `riverctl toogle-fullscreen` to chrome everytime.

**Comment by nagy135** [comment]
I m mostly using qutebrowser so this doesnt really bother me much (there you can also run videos via mpv), but i think there is no binary that works in arch repository now. I too didnt have luck making it work, there should be also this runtime option 
```
-enable-features=UseOzonePlatform -ozone-platform=wayland
```
but for me it crashes with
```
[48113:48190:0716/171653.217222:ERROR:wayland_event_watcher.cc(249)] Fatal Wayland communication error: Broken pipe
```
I forgot that I am again using chrome not chromium, because that sync thing doesnt work there anymore. That forces me to wait for binary that works and I think I will just move to firefox as @ifreund. If **anyone** got this working on chrome, please comment

**Comment by nagy135** [comment]
Nevermind, i found one that works ....in AUR we have also [this one](https://aur.archlinux.org/packages/google-chrome-beta/) and only with those flags from my comment above it works. It probably sends that request because it works as expected.
