### ISSUE TITLE
Crash when setting colour to empty string

### ISSUE THREAD

**Issue by Leon-Plickat** [ifreund/river#371]
I discovered this by accident: If you try to set any of the colours to an empty string, river crashes.

To reproduce:
```sh
riverctl border-color-focused ""
```

**Comment by ifreund** [comment]
Thanks for the report, fixed in 6f91011895de3db2cac0328a014c610d35411bce.

I really want to move this code outside of river...

**Comment by Leon-Plickat** [comment]
@ifreund we can actually move that code out of river in the short-term without redesigning all of river-control. We only need to extend river-control by a single request, `set_color`, which takes the colour name as string and four values for R G B and A (not sure if they should be int or float), so that riverctl does the hex parsing.

**Comment by ifreund** [comment]
> @ifreund we can actually move that code out of river in the short-term without redesigning all of river-control. We only need to extend river-control by a single request, `set_color`, which takes the colour name as string and four values for R G B and A (not sure if they should be int or float), so that riverctl does the hex parsing.

I don't think that kind of partial solution is worth the additional protocol complexity and inconsistency. I'd rather just wait and do a proper river-control protocol.
