### ISSUE TITLE
River soft-locks when layout generator exits while handling laoyut demand

### ISSUE THREAD

**Issue by Leon-Plickat** [ifreund/river#373]
It is possible to soft lock river if the the layout generator exits while handling a layout demand.

To reproduce, just place `std.os.exit(1)` somewhere in rivertiles layout demand handler, so that rivertile never sends the layout commit request.

Soft-locking means:
* tag switching does not work
* new views will never be displayed, but are focusable
* currently visible views are still focusable and can be interacted with
* views can not be moved via pointer

To unlock river, a new layout demand has to be triggered and succeed, for example by spawning a non-crashing layout generator. Note that the `riverctl output-layout <name>` command still works.

**Comment by ifreund** [comment]
Should be fixed by 9c633a78886eec86337438b2e3d4189197257464
