### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by lazy-dolphin** [ifreund/river#38]
`river` with single instances of `alacritty` and `htop` running consumes about 4-5% of CPU. Opening 10 more instances of `alacritty` sharply raises CPU usage of `river` to about 9-10%.

**Comment by ifreund** [comment]
Implementing damage tracking should fix this.

**Comment by n1rdeks** [comment]
on git version 3.2021 this situation duplicated: "river with single instances of foot and htop running consumes about 4-5% of CPU. Opening 2 more instances of foot sharply raises CPU usage of river to about 9-10%."

**Comment by wrkzk** [comment]
Can confirm this happens to me too. Top running inside of foot uses about 4% of CPU.

**Comment by Leon-Plickat** [comment]
It literally affects every single user, so I advice to refrain from adding duplicate reports. It is a known issue that will be resolved eventually.

**Comment by ifreund** [comment]
This can be tracked by  #206
