### ISSUE TITLE
Get position and dimensions of specific window

### ISSUE THREAD

**Issue by mitinarseny** [ifreund/river#386]
It would be great if there is a way to get current or any other window dimensions and it’s position on output. Possibly it can be implemented in riverctl. Something like:
```ah
riverctl get-dimensions current
```

it can be useful in pair with [slurp](https://github.com/emersion/slurp)/[grim](https://github.com/emersion/grim) to take screenshots

**Comment by Leon-Plickat** [comment]
I think this information would just be abused for weird hacks.

For the use case you mentioned it would be better to wait for wlroots to support recording individual toplevels.

**Comment by Leon-Plickat** [comment]
Closing for now.

Feel free to reopen if you have a good use case that has not been discussed yet.
