### ISSUE TITLE
Views appearing while in fullscreen are not focused when currently focused view is destroyed

### ISSUE THREAD

**Issue by Leon-Plickat** [ifreund/river#390]
To reproduce:

1. focus empty tag
2. spawn terminal
3. fullscreen terminal
4. spawn additional terminal
5. leave fullscreen
6. close focused terminal (either with keybind or by exiting the shell)
7. other terminal will remain the only visible view, but won't be automatically focused

**Comment by ifreund** [comment]
Fixed by 1baf3bf4622f88b83c84008fd19d0f9d2dd573c7
