### ISSUE TITLE
panic in getEffectiveResolution after display disconnect

### ISSUE THREAD

**Issue by edrex** [ifreund/river#393]
Panic moments after unplugging second display. Just once so far. i915.

```
$ coredumpctl debug
(gdb) bt
...
#4  0x000000000021c01f in std.builtin.default_panic
    (msg=..., error_return_trace=0x2) at /usr/lib/zig/std/builtin.zig:690
#5  0x0000000000257209 in Output.getEffectiveResolution (self=<optimized out>)
    at Output.zig:261
#6  Output.arrangeLayers (self=0x1000000, target=unmapped) at Output.zig:210
#7  0x000000000025eb20 in LayerSurface.handleCommit
    (listener=<optimized out>, wlr_surface=<optimized out>)
    at LayerSurface.zig:148
#8  .wayland.wayland_server_core.struct:490:17.wrapper
    (listener=<optimized out>, data=<optimized out>)
    at /home/eric/src/github.com/ifreund/river/zig-cache/zig-wayland/wayland_server_core.zig:492
...
```

LMK what else would be helpful to share

**Comment by ifreund** [comment]
Hmm, could you confirm that you are running with commit 2fc0875a3e17a0328d14d0c6323bd8022d5b15de? This stack trace looks very familiar to the the bug fixed by that.

**Comment by edrex** [comment]
Ah, my build was 2 commits behind at 2f3fe50 so I'll close this. 

thanks

**Comment by ifreund** [comment]
Just took another closer look at this stacktrace since @elshize reported a crash on unplugging an external monitor while running a build that included 2fc0875a3e17a0328d14d0c6323bd8022d5b15de and I think this is likely a different bug. At any rate it deserves closer investigation to see if we have a race causing a potential crash in the layer surface commit handler when outputs are destroyed.

**Comment by ifreund** [comment]
This may be fixed by 1e18ac9d7468c5d37f9c43587e8d87bf81c1f7ca. I can't say for sure though as I cannot reproduce.

**Comment by elshize** [comment]
Thanks @ifreund already updated and will let you know if I experience more crashes.

**Comment by edrex** [comment]
Alright, I updated too and I'll keep an eye out. I'm going to close this until such time as ...

**Comment by elshize** [comment]
Fwiw I haven't had a crash so far.
