### ISSUE TITLE
Separate styling for each border

### ISSUE THREAD

**Issue by deifactor** [ifreund/river#396]
My sway setup has a titlebar that was mostly useful, not for the title itself, but because it meant the active window had a nice thick bright blue line above it:

![image](https://user-images.githubusercontent.com/30192992/129157189-5ce3d5cb-35b9-4940-a2b5-abdec4169058.png)

You could replicate a similar effect just by adding border-{top,bottom,left,right}-{focused,unfocused,pixels} options. A titlebar would be neat too, but this seems easier and gets 80% of the way there.

If you think this would be a good first project for someone who's done C/C++/Rust but never Zig, I'm happy to work on it!

**Comment by ifreund** [comment]
Unfortunately I'm not interested in making river's cosmetic configuration more complex than it current is anytime in the near future. The focus of development is currently on core functionality and bug fixes.
