### ISSUE TITLE
[Yo] proper way to reload?

### ISSUE THREAD

**Issue by KingTheGuy** [ifreund/river#398]
i added this line to the init file
riverctl map normal $mod+Mod1 R spawn "~/.config/river/init"

pretty much reloading river. I'm not sure if there is something bad happening in the background but this is working pretty well for me.

**Comment by FoundOne** [comment]
It can mess up the things, if you spawn some extra processes, like I do, which can be solved with some extra code.

**Comment by ifreund** [comment]
You may be interested in #392. Beyond that though I don't intend to implement any other features to support this use-case.
