### ISSUE TITLE
Neither nested or real river instance works

### ISSUE THREAD

**Issue by Meister1593** [ifreund/river#408]
OS: Arch linux
DM: SDDM
DE: Plasma wayland (out of which it's running nested)
GPU: RX 480

Basically, my river instance is non-interactive, i can't do anything in it, nor programs would run in it (even if i would run it via init). It's basically empty blueish background and nothing else

First time i tried using AUR package ([this one](https://aur.archlinux.org/packages/river-git/)), i copied example script and tried running in nested session but i couldn't interact with it at all, nothing worked
Tried making .desktop file and running it out of sddm - same issues
Then i decided maybe it's something wrong with aur package and compiled it locally how it was described in this repo readme, tried running it out of `~/.local/bin/river` but it still didn't work, everything is the same

[River log](https://gist.github.com/Meister1593/625af0b8976de96169535e9f1ba8ef3a)

**Comment by ifreund** [comment]
river itself looks to be working just fine from that log. The issues is likely in your init script. Are you sure that `riverctl` is in your `$PATH` for example?

**Comment by inoshy** [comment]
hmm...basically the same problems that I had at first.
The blue background indicates that river is working, and non-interactive might mean that appropriate apps are not mapped to your key bindings. river assumes `foot` to be your default terminal. maybe change the init file to your likings and river would behave normally.

**Comment by Meister1593** [comment]
> river itself looks to be working just fine from that log. The issue is likely in your init script. Are you sure that `riverctl` is in your `$PATH` for example?

yeah i can run it outside river just fine (not accounting for not-launched river errors)

**Comment by Meister1593** [comment]
> hmm...basically the same problems that I had at first.
> The blue background indicates that river is working, and non-interactive might mean that appropriate apps are not mapped to your key bindings. river assumes `foot` to be your default terminal. maybe change the init file to your likings and river would behave normally.

i can't even run meta + shit + e to exit river, so it's most likely something else

**Comment by Meister1593** [comment]
> > hmm...basically the same problems that I had at first.
> > The blue background indicates that river is working, and non-interactive might mean that appropriate apps are not mapped to your key bindings. river assumes `foot` to be your default terminal. maybe change the init file to your likings and river would behave normally.
> 
> i can't even run meta + shit + e to exit river, so it's most likely something else

Oops my bad, i can actually run it, not sure why i couldn't before... (probably forgot about shift)

**Comment by Meister1593** [comment]
It seems that it started working, not sure why it didn't before, issue may be closed i think

**Comment by inoshy** [comment]
good to know its working. you will find river great and stable.
