### ISSUE TITLE
Mapping to key chain

### ISSUE THREAD

**Issue by marcosrdac** [ifreund/river#409]
Hello! I'm trying to configure river so that I can use it more or less how I use bspwm, more specifically, how I use sxhkd.

There we can have a combination of keys mapped to call a command. This can be used to make some kind of semantic, or some kind of keymap grammar. For example: all the keymaps I set to open programs on new windows start with `Alt+w`. Therefore, opening my browser is mapped to `Alt+w b` (where b is pressed after the first combination of keys, `Alt+w`).

How could I do something like that in here? I really miss this feature. Do you think of a way I could implement this as a shell script or so?

**Comment by maringuu** [comment]
I think you could use modes:
```sh
riverctl declare-mode alt_w
riverctl map normal Mod3 w enter-mode alt_w
riverctl map alt_w spawn "$browser || riverctl enter-mode normal"
```

**Comment by ifreund** [comment]
Modes are indeed the way to achieve this behavior. Maringuu's example looks good except for the final line which has a few typos. This should work:
```
riverctl map alt_w None b spawn "firefox; riverctl enter-mode normal"
```

**Comment by marcosrdac** [comment]
Thank you all! It works nicely :)
