### ISSUE TITLE
No documentation for how to tile on startup:

### ISSUE THREAD

**Issue by ideasman42** [ifreund/river#412]
From reading over the docs there is no info on how to tile on startup.

- `rivertile -outer-padding 1 -view-padding 0 -main-location top -main-ratio 0.5`
- `riverctl output-layout rivertile`

These two commands do tile the current output, but I would like to start tiled.

#192 hints that this is possible, but I'm not sure how it should be achieved.

**Comment by ifreund** [comment]
Hi, it looks like you're looking for the `riverctl default-layout` command. This is documented in the `riverctl(1)` man page and in the example init file.
