### ISSUE TITLE
[Feature request] Monocle mode

### ISSUE THREAD

**Issue by sagehane** [ifreund/river#414]
I read the manpage + sample init file and was unable to find anything relevant, so I'm presuming it currently doesn't exist.
Something like a monocle mode from dwm (mod + m) or tabbed layout from i3 (mod + w) would be appreciated.
Sorry beforehand if I overlooked something silly.

Relevant issues/PRs:
https://github.com/ifreund/river/pull/5#issuecomment-616084326 (Seems to imply that monocle was a thing at one point?)
https://github.com/ifreund/river/issues/26 (Seems to talk under the assumption that monocle is a thing)

**Comment by ifreund** [comment]
You're right that monocole mode doesn't exist in the `rivertile` layout generator shipped with river. However, river allows users to implement their own layout generators which may do whatever the user wants with regards to layouts, including a monocle mode.

See this wiki page for a few already existing layout generators for river: https://github.com/ifreund/river/wiki/Community-Layouts

In particular, I see on that page that rivercarro has a monocle mode.

**Comment by sagehane** [comment]
Thanks. I tried `rivercarro` and got the functionality I wanted. Is there any reason why monocle is out of scope for `rivertile`?

**Comment by ifreund** [comment]
> Thanks. I tried `rivercarro` and got the functionality I wanted. Is there any reason why monocle is out of scope for `rivertile`?

rivertile is just the arbitrary set of features I personally feel like maintaining in this repo. So no, there's no good reason, I expect most users of river to use a more fully-featured layout generator.
