### ISSUE TITLE
Add `send-to-previous-tags` command.

### ISSUE THREAD

**Issue by Leon-Plickat** [ifreund/river#416]
Mostly for consistency, as all focus commands have corresponding move commands, except for `focus-previous-tags`.

**Comment by ifreund** [comment]
I don't think we should add things just for the sake of consistency if they won't actually be used in practice, and I don't see myself ever using a `send-to-previous-tags` command personally. Would you make use of this command?

**Comment by Leon-Plickat** [comment]
I don't know if I'd ever use it, I mainly proposed it for the sake of symmetry.

Although on the other hand I also thought I'd never use `focus-previous-tags` until it got implemented and now I use it frequently to flip back and forth between two tag-sets. Not sure yet if I would benefit from the ability to take views with me when doing so.

**Comment by ifreund** [comment]
Fair enough, I guess the only way to know is to implement and see if it makes it seems useful.
