### ISSUE TITLE
Cannot launch river: wlroots libseat errors

### ISSUE THREAD

**Issue by buttke** [ifreund/river#417]
Hello, I'm running Arch and trying to run river from tty. I have libseat 0.5.0-2 installed. Here's my  output:
```
buttke@computer$ river

info: initializing server
error(wlroots): [libseat] [libseat/backend/logind.c:267] Could not activate session: Permission denied
error(wlroots): [libseat] [libseat/libseat.c:55] Backend 'logind' failed to open seat: Resource temporarily unavailable
error(wlroots): [backend/session/session.c:84] Unable to create seat: Resource temporarily unavailable
error(wlroots): [backend/session/session.c:218] Failed to load session backend
error(wlroots): [backend/backend.c:353] Failed to start a DRM session
error: BackendCreateFailed
???:?:?: 0x23211c in ??? (???)
???:?:?: 0x232158 in ??? (???)
???:?:?: 0x22ffbe in ??? (???)
```
This was achieved using the default `init` file.

**Comment by buttke** [comment]
I ended up installing sway to check if this was a wlroots problem. After installing sway, river can launch. Perhaps a dependency was missing in the river-git aur package?

**Comment by ThreeFx** [comment]
Yeah, you are probably missing `polkit`. This is an Arch Linux packaging issue though, and should be reported in the [AUR](https://aur.archlinux.org)

**Comment by andreafeletto** [comment]
I've added `polkit` to the AUR package dependencies.
