### ISSUE TITLE
[Question] Change color of the borders

### ISSUE THREAD

**Issue by uncomfyhalomacro** [ifreund/river#421]
I really love this tiling window manager. Thank you devs❤️. Now to the point at hand, is there a way to change the colors of the borders? as of now, i can only see that it is whitish-gray something, have i missed something or is that the only color of the borders for now and no manual intervention in the configuration can be done with it?

**Comment by inoshy** [comment]
Yea there is. see this : https://github.com/ifreund/river/blob/master/doc/riverctl.1.scd#configuration

or you can just `man riverctl`

**Comment by uncomfyhalomacro** [comment]
thanks. i am so stupid for not thinking of that lel

**Comment by inoshy** [comment]
its fine :) also you can check `man river` and `man rivertile` for additional options as well.
