### ISSUE TITLE
Strange behavior when mapping just the Logo key [BUG?]

### ISSUE THREAD

**Issue by user18130814200115-2** [ifreund/river#422]
There is some strange behavior when attempting to make a mapping to **just** the logo key.
Example:
`riverctl map normal None Super_L spawn xyz`
works, while:
`riverctl map -release normal None Super_L spawn xyz`
does not.

This can be fixed on the user side by using:
`riverctl map -release normal Mod4 Super_L spawn xyz`

I am not sure if this is a bug or intended behavior. Furthermore, I do not feel like this bug has a high-priority since there is a workaround, but I felt like it should be reported nonetheless.

**Comment by Leon-Plickat** [comment]
This may seem a bit strange, but it makes perfect sense considering that Super is Mod4.

Modifier handling "lags behind" keybind handling. When you press Super, it first execs your keymap, then adds Mod4 to the modifier state. If you release Super, it first execs your keymap, then removes Mod4 from the modifier state. Therefore,  the press-map is unmodified while the release-map has Mod4 as modifier.

**Comment by ZerdoX-x** [comment]
@user18130814200115-2 Thank you for workaround so much!
I need this after migrating from i3 where you can bind modifier with release.

My usecase:

```
riverctl map -release normal Mod4 Super_L spawn wofi --show drun
```

However with `None` modifier it doesn't work. And it does work without `-release` parameter. I think this is a bug.

**Comment by Leon-Plickat** [comment]
> I think this is a bug.

Please read my explanation above why this is not a bug.

BTW, you need to quote the command you want to spawn.

```c
riverctl map -release normal Mod4 Super_L spawn wofi --show drun   # this is wrong
riverctl map -release normal Mod4 Super_L spawn "wofi --show drun" # This is right
```

> I tested it out and this binding causes spawning even when I trigger other actions like "close". :(

Of course it does. When You press for example `Super_L+S`, river will see:

1. `Super_L` pressed
2. `S` pressed
3. `S` released
4. `Super_L` released

Each of these events is individually checked for a matching keymap.

If you'd prefer this to work differently, please open a new issue with a proposal so it can be discussed.

**Comment by ZerdoX-x** [comment]
For anyone who tries to achieve same effect, use [dual-function-keys](https://gitlab.com/interception/linux/plugins/dual-function-keys). I binded opening launcher on `Super_R` and it triggers when I tap, but when I hold it it likes like `Super_L`.
