### ISSUE TITLE
Focus-follows-cursor doesn't change the focused output

### ISSUE THREAD

**Issue by subsetpark** [ifreund/river#425]
I have focus-follows-cursor on and it works normally within a single output.

Across multiple outputs: the focused view *does* change, regardless of what output it's on. If i move my cursor from one output to another, the focused view is always the one under the cursor.

However: I would expect the focused *output* to change as well. That is, when I spawn a new terminal, I would expect it to spawn under the tag and output that my cursor is currently under. 

Instead, the terminal spawns in the same output regardless. I have to call `focus-output` in order to actually change the destination output for a new window.

**Comment by subsetpark** [comment]
Closing: it requires clicking as well. A little unintuitive but I can work with that.

**Comment by ifreund** [comment]
I believe what you're running into here is that focus-follows-cursor currently only works when moving your cursor over views, not over the background of an empty output. If I move my cursor over a view on a different output, new views are created on that output without any clicking required.

I'm open to merging a patch to modify the behavior of focus follows cursor to change focus even if there is no view under the cursor, but I don't use focus follows cursor so I'm unlikely to implement that myself.
