### ISSUE TITLE
XWayland: Windows that are "minimized to tray" cannot be brought up again.

### ISSUE THREAD

**Issue by pmkap** [ifreund/river#436]
The apps I observed this are qbittorrent and mullvad-vpn.

**Comment by Leon-Plickat** [comment]
It would be important to know how these X clients "minimize" their window. There are two common methods: **a)** destroy the window and recreate it when it is needed again and **b)** unmap the window and re-map it once it is needed again. I suspect its b).

I don't think there is any X test suite ready to use; If I find some time this week I'll try to write an X client that does unmapping and re-mapping to figure this out.

**Comment by uncomfyhalomacro** [comment]
i was about to open an issue about this as well, and it also happens to discord, slack, and caprine.

**Comment by Leon-Plickat** [comment]
Just managed to reproduce with a minimal text client.

Re-mapping a previously mapped then unmapped window does not work (however from the X clients POV the operation does not fail).

**Comment by inoshy** [comment]
noice noice
xwayland is buggy as hell

**Comment by ifreund** [comment]
Should be fixed by 9270a2df08b8fad97203baedf133ac0b4fc47048
