### ISSUE TITLE
Unable to launch river via the tty

### ISSUE THREAD

**Issue by idontknowwhatimdoing** [ifreund/river#438]
After login, running `river` in the tty fails with the following error message:

info: initializing server
error (wlroots): [libseat] [libseat/backend/seatd.c:781] Could not connect to socket /run/seatd.sock: No such file or directory
info (wlroots): [libseat] [libseat/libseat.c:70] Backend 'seatd' failed to open seat, skipping
info (wlroots): [libseat] [libseat/libseat.c:67] Seat opened with backend 'logind'
info (wlroots): [backend/session/session.c:1101] Successfully loaded libseat session
info (wlroots): [backend/backend.c:223] Found 1 GPUs
info (wlroots): [backend/drm/backend.c:182] Initializing DRM backend for /dev/dri/card0 (i915)
info (wlroots): [backend/drm/drm.c:259] Found 3 DRM CRTCs
info (wlroots): [backend/drm/drm.c:186] Found 24 DRM planes
MESA-LOADER: failed to open iris: /run/opengl-driver/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver/lib/dri, suffix _dri)
failed to load driver: iris
MESA-LOADER: failed to open kms_swrast: /run/opengl-driver/lib/kms_swrast_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver/lib/dri, suffix _dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast: /run/opengl-driver/lib/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver/lib/dri, suffix _dri)
failed to load swrast driver
error (wlroots): [backend/drm/renderer.c:29] Failed to create GMB device
error (wlroots): [backend/drm/backend.c:237] Failed to initialize renderer
error (wlroots): [backend/backend.c:230] Failed to create DRM backend
error (wlroots): [backend/backend.c:371] Failed to open any DRM device
error: BackendCreateFailed
???:?:?: 0x22bbe7 in ??? (???)
???:?:?: 0x22bc23 in ??? (???)
???:?:?: 0x22940e in ??? (???)

**Notes**: I am on Arch Linux and i installed river with the nix package manager
uname -a: `Linux monkaS 5.14.7-arch1-1 #1 SMP PREEMPT Wed, 22 Sep 2021 21:35:11 +0000 x86_64 GNU/Linux`
nix-env -q: `nix-2.3.15  river-unstable-2021-08-03`

Let me know if you need more information.

**Comment by novakne** [comment]
I would guess you don't have mesa driver installed

**Comment by ifreund** [comment]
I'd recommend you try building from source or using the AUR package instead of nix, I suspect that's what's causing you problems.

**Comment by inoshy** [comment]
Are you using nvidia card?

**Comment by idontknowwhatimdoing** [comment]
> Are you using nvidia card?
No I'm not, I have a Intel graphic card.

II realized that my versions of zig and wlroots were not the same that the ones specified on the README, so i am currently in the process of installing those with the right version.
I'll update later.

**Comment by inoshy** [comment]
yup. river is great. it would be really sad if you could not use it.

**Comment by ifreund** [comment]
To be clear, wlroots 0.14.1 and zig 0.8.1 would work fine as well. Are you certain that you initialized the git submodules with `git submodule update --init`? Do you have `pkg-config` and `wayland-protocols` installed?

Since you are on arch, does the AUR package compile successfully? That would rule out any missing dependencies...

**Comment by idontknowwhatimdoing** [comment]
> Are you certain that you initialized the git submodules with git submodule update --init? Do you have pkg-config and wayland-protocols installed?

Yes and yes.
After clearing the previous zig and wlroots (my bad I thought the versions needed to be exact), trying to install the AUR package gives me a similar error message (a bunch of compilation errors), I can post it if you want.

**Comment by inoshy** [comment]
please post it. I am very curious because I had not encountered such error messages on Arch.

**Comment by idontknowwhatimdoing** [comment]
Here is the pastebin containing the full yay command [https://pastebin.com/HUCuf4xQ](url)

**Comment by inoshy** [comment]
> Here is the pastebin containing the full yay command [https://pastebin.com/HUCuf4xQ](url)

The link points back to https://github.com/ifreund/river/issues/url :D

**Comment by inoshy** [comment]
I am sorry that I can't give a clear indication on whats going wrong. can be conflicting versions of dependencies. is a fresh install of arch an option for you?

**Comment by andreafeletto** [comment]
Could you please list the versions of the dependencies in your system?
If the problem is an old dependency, I can add the requirement to the PKGBUILD.
Right now the only packages with version requirements are wlroots, zig and mesa.

**Comment by idontknowwhatimdoing** [comment]
> Could you please list the versions of the dependencies in your system?

zig:                          0.8.1
wayland:                 1.19.0
wayland-protocols:  1.23
wlroots:                    0.14.1
libevdev:                  1.11.0
xkbcommon:            1.3.1
pixman:                    0.40.0
pkgconf:                   1.8.0
mesa:                       21.2.2

**Note:** [https://aur.archlinux.org/packages/river-git](url) it looks like there is currently a version mismatch with glibc that is causing build errors. I will try the suggested fix later.

> is a fresh install of arch an option for you?

I can try to spin up a fresh arch VM when I have time, I'll look into it if the problem persists.

**Comment by ifreund** [comment]
> Update 2: I started a fresh arch VM and was able to install the AUR package without any problem.

Seems like this was a system configuration issue of some kind then...
