### ISSUE TITLE
Views doesn't respect screen limit and paddings

### ISSUE THREAD

**Issue by mfxarc** [ifreund/river#439]
All screenshots were printed while using river with rivertile as default layout and without being float mode.
In this case, one view get over the other without respecting a limit:
![26-09-21-14:24](https://user-images.githubusercontent.com/91107012/134824857-035e0e63-1b9c-46d3-931f-99db50169957.png)
And in this, the view get off of the screen:
![26-09-21-14:24](https://user-images.githubusercontent.com/91107012/134824969-38b48581-7213-4fdc-8dee-d788e3a1b594.png)
The use of Brave Browser is just for demonstration, the bug happens with any software.

**Comment by Leon-Plickat** [comment]
Not a bug.

River simply respects the minimum and maximum size of views.

If the minimum/maximum size of a view is inconvenient, that is a bug with that client, not river.

**Comment by ifreund** [comment]
We do have the option of cropping views that extend past the bounds river wants to those bounds. This may make some programs unusable though.
