### ISSUE TITLE
Update dependencies for NixOS build

### ISSUE THREAD

**Issue by vizs** [ifreund/river#44]
`river` does not build with the given nix derivation in the wiki, I had to add libGL to buildInputs (my shell.nix file -- http://0x0.st/iOlR.txt)

Also the link to config.zig in README is outdated.

**Comment by ifreund** [comment]
Hey, thanks for letting me know about the broken link in the readme. I don't use NixOS personally, so I don't really feel qualified to tell people how to build river on it. I think I've succeeded in making the wiki world-editable, so feel free to modify that page as you see fit. If it won't let you for some reason, let me know.

**Comment by vizs** [comment]
Well, in that case, I hope it is okay if I replace the current nix expression with mine and close the issue?

**Comment by ifreund** [comment]
Yes, please do!

**Comment by vizs** [comment]
Updated :)

**Comment by ifreund** [comment]
I must admit I'm a little confused though, LibGL is present in both lists no?

**Comment by vizs** [comment]
No, libGL wasn't present in the previous expression. I don't think Nix includes libGL when wlroots get includes in `buildInputs`

**Comment by ifreund** [comment]
It's there, as is `pkg-config` which I think is also required no?
```nix
with import <nixpkgs> {};
stdenv.mkDerivation rec {
	name = "river";
	buildInputs = [
		pkgs.zig
		pkgs.wayland
		pkgs.wayland-protocols
		pkgs.wlroots
		pkgs.libxkbcommon
		pkgs.pkg-config
		pkgs.libudev
		pkgs.libGL
		pkgs.xorg.libX11
		pkgs.pixman
	];
}
```

**Comment by vizs** [comment]
Oh, I must have accidentally deleted it or something when I was writing my own, my bad. Also, you're supposed to include compile time tools like pkgconfig to `nativeBuildInputs`.

**Comment by ifreund** [comment]
Cool, i guess yours is technically more correct then :D
