### ISSUE TITLE
Add AUR package

### ISSUE THREAD

**Issue by appetrosyan** [ifreund/river#45]
Hi. 

Love the idea. Want to help out with deploying to the AUR.

**Comment by ifreund** [comment]
I actually put up an AUR package a while back: https://aur.archlinux.org/packages/river-git/

However, I'm not using arch any more so if you'd like to be added as a comaintainer just let me know your username.

**Comment by appetrosyan** [comment]
Ah! Great! It's `appetrosyan`.

**Comment by ifreund** [comment]
cool, added you.
