### ISSUE TITLE
mpv not resizing in floating mode with own keybindings

### ISSUE THREAD

**Issue by fun0fun** [ifreund/river#451]
Hi. Tested `mpv` in `river` and looks like it's bindings for changing window size not working as expected. When pressing `alt+0` it should change window size to 50% and return to 100% with `alt+1`. And it's not reacting anyhow in the river. 

Tested in `sway` and it's working as expected.

Hope we can get it working in `river` as well.

Thank you.

**Comment by ifreund** [comment]
> Thanks for the advice. It is better now, but still buggy. When using alt+0, and it changing to half size from 4k, it moves the window to upper left corner and then I am unable to snap or move window to the right or bottom. It's moving inside small invisible frame, little bigger then mpv window.

These bugs should be fixed by b9861961182e49c5be10929bd2f2b4d6c6d19677

I'll open a new issue to discuss the fact that river sets the tiled state for all views not in csd-filter currently
