### ISSUE TITLE
Tag management is not working

### ISSUE THREAD

**Issue by Sprite36** [ifreund/river#460]
I'm trying to write the init script in c++ . But the tag management won't work. My code is: 
```
system("riverctl map normal Mod4 1 set set-focused-tags 1");
system("riverctl map normal Mod4 2 set set-focused-tags 2");
system("riverctl map normal Mod4 3 set set-focused-tags 4");
system("riverctl map normal Mod4+Control 1 set-view-tags 1");
system("riverctl map normal Mod4+Control 2 set-view-tags 2");
system("riverctl map normal Mod4+Control 3 set set-view-tags 4");
```
Everything else seems to work perfectly.

**Comment by Leon-Plickat** [comment]
have you tried the commands you call using `system()` in your shell before? Because the ones you list above are definitely wrong, there should not be a `set` before `set-focused-tags`.

**Comment by Sprite36** [comment]
This fixed it thank you. I knew it was a problem with my config.
