### ISSUE TITLE
Idea: Attach commands to events

### ISSUE THREAD

**Issue by Leon-Plickat** [ifreund/river#52]
It might be helpful being able to attach executing commands to certain events.

Example use case: New outputs. When a new output becomes available, it needs to be setup to become usable (meaning choosing a layout, setting a wallpaper, adjusting desktop widgets, etc...).

I understand the current idea is to make `riverctl` able to continuously listen to events. However I think directly attaching commands to events might be a bit nicer.

```sh
riverctl attach-event new-output "~/.bin/handle-new-output.sh"
```

Why nicer? If `riverctl` would be continuously listening, you either need a script which parses its output to find out what kind of event was received, or we need to adapt `riverctl` so that it can be setup to only listen to specific events, in which case multiple listeners would be running. Both of those approaches might be "unix-y", but I don't think they scale very well. In fact, having a `riverctl` listening in the background requires shell job control, which has the potential to get messy. In comparison, executing a (single) command on specific events (new output, new input, etc...) solves this better while being basically trivial to implement in river.

With this approach, the command executed on an event could even be changed at runtime, which is not easily doable with a listener script.

This probably does not fit the bspwm model, but it does fit the river model, as river already executes commands on certain events (keybinds).

**Comment by ifreund** [comment]
I agree, I've had vague plans for a feature like this for a while. I think I'd take a page out of Kakoune's book and call the command `hook` though. The other question becomes whether it should take a `river` command as it's second argument like `map` or if it should execute the argument with `spawn`. The former option could avoid unnecessary overhead in some cases and still allows for running an arbitrary command using `spawn`:

```sh
riverctl hook new_output spawn "~/.bin/handle-new-output.sh"
```

A couple of things to consider:

- Should the execution order for multiple hooks on the same event be reliable/defined? If so probably in the order of hook registration.
- Should hooks carry information with them? (e.g. a `focus_tag` hook might carry the tagmask). I'm inclined to say no and make relevant information queryable with separate command, which could of course be called from a script handling a hook.
- we probably need a `remove-hook` command alongside this. (and an `unmap` command, though that's a different issue.)

**Comment by ifreund** [comment]
A hook system like this could also be potentially be used for the common use cases of floating some classes of windows or always starting certain programs on a particular tag.
