### ISSUE TITLE
Idea: Draw borders around a windows actual size, not its expected size

### ISSUE THREAD

**Issue by Leon-Plickat** [ifreund/river#59]
Some applications, like a lot of GTK programs, enforce a minimum and sometimes even maximum size for its windows. Currently borders are always drawn around the expected window size. That however looks pretty bad when the window has a different size. We can not do anything about windows not respecting the size we ask them to abide to, but we should at least handle that case gracefully, by drawing the borders around a windows actual size.

**Comment by ifreund** [comment]
Related #10

**Comment by ifreund** [comment]
Implemented in 60f06a1a40d258a219ebef895d92fa1ceaf64fb7
