### ISSUE TITLE
river-status.seat_status_listener.{focused_output, unfocused_output} never called

### ISSUE THREAD

**Issue by dnkl** [ifreund/river#69]
Not sure if you mentioned this on IRC, but I don't see any calls whatsoever to `focused_output()` and `unfocused_output()` in the seat-status interface. I **do** see calls to `focused_view()`.

My intention was to use this information to differentiate between focused and unfocused (as in, has keyboard/pointer focus or not) _visible_ tags (i.e. tags that are focused by any output).

**Comment by ifreund** [comment]
Hmm, there are calls in the code at least and I have a vague memory of testing it, but it could easily be broken currently. I will investigate later this evening, thanks for trying it out!
https://github.com/ifreund/river/blob/3bc799811ff6ae4e034f48c55f1b3f8c4e2fd3f4/river/SeatStatus.zig#L71-L72

**Comment by ifreund** [comment]
As far as I can tell, this is working as intended. Using the [example client](https://github.com/ifreund/river/blob/master/example/status.zig) (which can be built by passing `-Dexamples=true`) I get a `focused_output` event on creating the `river-seat-status` object and receive further `focused_output`/`unfocused_output` events on switching between outputs.

Could you check if this works for you using the example client? If it doesn't I'm sure a `WAYLAND_DEBUG=1` log would be useful.

**Comment by ifreund** [comment]
Oh, I realized that events will only be sent if the client has bound the `wl_output` globals which would be referenced. Don't think there's any good way around that but it might be worth mentioning in the protocol.

**Comment by dnkl** [comment]
Thank you for pointing that out! I guessed as much, and did in fact bind 
the output globals.

But the seats, and the river seat status interfaces were bound before the 
outputs (because river sent them in that order). That meant I missed the 
initial call, and since I only had one output I never saw any other 
calls...

Special casing (delaying) the instantiation of the river status 
interfaces during startup solved this.

Thanks!

**Comment by ifreund** [comment]
No problem! I just added a note about this to the protocol in order to avoid any confusion/wasted time debugging in the future.

**Comment by dnkl** [comment]
Great! I've also tested my implementation on a multi-output system and everything Works As Intended :tm: So, all good!

**Comment by dnkl** [comment]
I'm looking at a different workaround, where I re-bind the river seat status objects (for all seats) whenever an output object is added.

In other words, each time I see an output global, any existing `zriver_seat_status_v1` objects are **destroyed** (there's no release function?), and then re-created.

Will this cause any issues in river? Leaks?

**Comment by ifreund** [comment]
> I'm looking at a different workaround, where I re-bind the river seat status objects (for all seats) whenever an output object is added.
> 
> In other words, each time I see an output global, any existing `zriver_seat_status_v1` objects are **destroyed** (there's no release function?), and then re-created.
> 
> Will this cause any issues in river? Leaks?

@dnkl That should be fine, it'll cause a little bit more memory allocation churn on river's side I guess but nothing to be concerned about in practice. 

Really, river should fix this the way wlroots does for e.g. wl_surface.enter/leave by keeping a flag for every seat_status/client/output combination of whether the initial event has already been sent or not and if it has not yet been sent when the output is bound send it then. I'd be happy to accept a patch doing this but don't have time to implement it myself in the near future unfortunately.

**Comment by MaxVerevkin** [comment]
Sending these events for late-bound outputs shouldn't be hard, see a similar PR for hyprland - https://github.com/hyprwm/Hyprland/pull/1480/files, which in turn is based on https://github.com/swaywm/wlroots/pull/2468. Do you think this is a bug that should be fixed (I can try doing so), or do you prefer the current state because it slightly reduces complexity?
