### ISSUE TITLE
Feature request: Naming tags

### ISSUE THREAD

**Issue by Leon-Plickat** [ifreund/river#72]
I am proposing a new property of tags: Names. This would only be additional data, the current workflow using the numbers / "ids" / bit fields to identify tags would remain unchanged.

The idea is to provide a way for the user to be more organized / to easier find the correct tag.

Example: I switch to tag 8 and place my mail client here. I name this tag "mail" (`riverctl name-tag mail`). A hypothetical status bar would display the tag along with its name. If I now work in different tags, I do not need to remember what tag my mail client is on, as the status bar just displays it.

I currently do this with sway workspaces, which has increased my efficiency a lot, so I would like to bring the same functionality to river.

As a reference, here is a picture of my sway status bar. As you can see, this avoids getting lost in your workspaces / tags.
![good-bar](https://user-images.githubusercontent.com/49593314/88450528-f5cfdc80-ce4f-11ea-84f7-37578d71b8a4.png)

I am willing to implement this myself, but I thought getting some feedback first might be a good idea.

**Comment by ifreund** [comment]
Does this need to be done in river? Couldn't the status bar just do the name to number translation?

**Comment by Leon-Plickat** [comment]
Hmmm... I think that requires some experimentation.

I'll do that and report back.
