### ISSUE TITLE
[feature request] focus follows cursor

### ISSUE THREAD

**Issue by hollmmax** [ifreund/river#78]
Many tiling window managers can be setup to change the active window whenever the cursor moves, to the window currently under the cursor. I'd find it useful to have an option like this in river too.
This is most useful on laptops, where swiping with thumb is often faster than a keyboard shortcut.

**Comment by pithuene** [comment]
This would be great.
Personally I would like focus to change only on click though. I regularly find myself scrolling in one window while writing in another. Maybe that could be made optional?

**Comment by ifreund** [comment]
> Maybe that could be made optional?

That would be a requirement for implementing this feature, as I personally would not use it. However, I think this is something we want to have eventually and shouldn't be all that complex to implement.
