### ISSUE TITLE
Parts of windows are not visible as they go 'out of screen'

### ISSUE THREAD

**Issue by lazy-dolphin** [ifreund/river#8]
river assumes I am running it on a larger display. My monitor's screen resolution is 1366x768. For instance,
![20200426_15h14m39s_grim](https://user-images.githubusercontent.com/51233180/80306911-97a94400-87e3-11ea-9284-c7a0f6cf27bf.png)

**Comment by ifreund** [comment]
Hmm, I'm not quite sure what's happening here.  Nested wayland sessions of river always seem to adapt to the size of the window they run in, and running from a tty works for me on a 1920x1080 display. Will have to investigate, probably not doing the detection entirely right.

**Comment by lazy-dolphin** [comment]
Changing 1920 to 1366 and 1080 to 768 in output.zig solves this for now though.

**Comment by ifreund** [comment]
Oh, i forgot I had that hardcoded. That will have to change, thanks for investigating.

**Comment by ifreund** [comment]
Could you confirm that https://github.com/ifreund/river/commit/c5826b04f41a05c6a631759c5a1d26211aaeef10 fixes this @lazy-dolphin?

**Comment by lazy-dolphin** [comment]
Works!
