### ISSUE TITLE
Issues With XWayland

### ISSUE THREAD

**Issue by BenEvolent333** [ifreund/river#82]
Hello! I've been toying around with river for a bit, but I can't get XWayland to work. Every time I try to open an Xorg app, ~~I get the error "cannot open display: "~~. I've never tried a Wayland compositor before, so I understand I'm probably doing something wrong. I need this to work before I can do anything more serious with it. I have tried it on tty2 while lightdm is running on tty7, as well as with lightdm disabled and Xorg not running.

Edit: I get a different error, "unable to open X display," this time. Last time I had the variable $DISPLAY set, just set to an empty string

**Comment by ifreund** [comment]
I'm going to assume that the fix was building river with `-Dxwayland=true`? Do note that XWayland is not very well tested as of yet as I personally rarely use it. So, if you notice any odd behavior please open a bug report.

**Comment by BenEvolent333** [comment]
Yes, that was the fix. I tried to use "man river" but I installed the man to /usr/local/man, so nothing came up. I do have one issue, which is that neither polybar nor lemonbar open correctly (both open as if they were a regular window).

On August 9, 2020 8:32:50 AM UTC, Isaac Freund <notifications@github.com> wrote:
>I'm going to assume that the fix was building river with `-Dxwayland=true`? Do note that XWayland is not very well tested as of yet as I personally rarely use it. So, if you notice any odd behavior please open a bug report.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/ifreund/river/issues/82#issuecomment-671024150
-- 
Sent from my Android device with Librem Mail. Please excuse my brevity.

**Comment by ifreund** [comment]
> I do have one issue, which is that neither polybar nor lemonbar open correctly (both open as if they were a regular window).

These likely won't work too well with wayland, I'd recommend giving [waybar](https://github.com/Alexays/Waybar) or [yambar](https://codeberg.org/dnkl/yambar) a try. Both are wayland-native and have support for river's tags.

**Comment by BenEvolent333** [comment]
Thank you! I assumed there had to be something that would work. One more issue, I use notifications though dunst, which show up correctly in river, but when I click them nothing happens.

On August 9, 2020 8:54:23 PM UTC, Isaac Freund <notifications@github.com> wrote:
>> I do have one issue, which is that neither polybar nor lemonbar open correctly (both open as if they were a regular window).
>
>These likely won't work too well with wayland, I'd recommend giving [waybar](https://github.com/Alexays/Waybar) or [yambar](https://codeberg.org/dnkl/yambar) a try. Both are wayland-native and have support for river's tags.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/ifreund/river/issues/82#issuecomment-671099822
-- 
Sent from my Android device with Librem Mail. Please excuse my brevity.

**Comment by ifreund** [comment]
> One more issue, I use notifications though dunst, which show up correctly in river, but when I click them nothing happens.

Hmm, I think I probably just haven't implemented input handling for non-standard Xwayland views. Until I get around to that, I'd suggest something wayland-native like [mako](https://github.com/emersion/mako) or [fnott](https://codeberg.org/dnkl/fnott)

**Comment by BenEvolent333** [comment]
Ok, thank you!

On August 9, 2020 9:53:33 PM UTC, Isaac Freund <notifications@github.com> wrote:
>> One more issue, I use notifications though dunst, which show up correctly in river, but when I click them nothing happens.
>
>Hmm, I think I probably just haven't implemented input handling for non-standard Xwayland views. Until I get around to that, I'd suggest something wayland-native like [mako](https://github.com/emersion/mako) or [fnott](https://codeberg.org/dnkl/fnott)
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/ifreund/river/issues/82#issuecomment-671105414
-- 
Sent from my Android device with Librem Mail. Please excuse my brevity.

**Comment by BenEvolent333** [comment]
Is there a way to integrate River with the waybar in terms of tags? Like how herbstclient has a command which prints out the status of each workspace, i.e. which is active, which have windows open, and such?

On August 9, 2020 9:53:33 PM UTC, Isaac Freund <notifications@github.com> wrote:
>> One more issue, I use notifications though dunst, which show up correctly in river, but when I click them nothing happens.
>
>Hmm, I think I probably just haven't implemented input handling for non-standard Xwayland views. Until I get around to that, I'd suggest something wayland-native like [mako](https://github.com/emersion/mako) or [fnott](https://codeberg.org/dnkl/fnott)
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/ifreund/river/issues/82#issuecomment-671105414
-- 
Sent from my Android device with Librem Mail. Please excuse my brevity.

**Comment by ifreund** [comment]
The latest version of waybar has a `river/tags` module.

**Comment by BenEvolent333** [comment]
I have everything working mostly well now, thank you for all your help! The only remaining notes I had were 
- dmenu (the X11 version) draws itself over the bar at the top, and remains there after the process ends
- the window manager does not time out/blank, it remained on the screen for hours while I was away. I am happy to use waylock to lock the screen, but I would expect it to fade to black after a certain period of time
I am very happy with the progress so far! I assume the issue with dmenu (X11) has to do with damage control(?) which was mentioned in the XWayland part of the roadmap, and I am perfectly fine using bemenu and/or dmenu-wl instead. If you can tell me of a way to fix the second issue, then river will be my new full-time wm

**Comment by Leon-Plickat** [comment]
> * the window manager does not time out/blank, it remained on the screen for hours while I was away. I am happy to use waylock to lock the screen, but I would expect it to fade to black after a certain period of time

https://github.com/swaywm/swayidle

**Comment by ifreund** [comment]
Unfortunately `swayidle` won't work with river until we implement the [kde idle protocol](https://github.com/swaywm/swayidle/blob/master/idle.xml) it uses. Looks like I forgot to add this to the roadmap, but it shouldn't be too hard to implement and is fairly high on my todo list.

**Comment by ifreund** [comment]
implemented the protocol in 7de2edb623bc5f4f13a591da7bbff7a47e1c6e58, `swayidle` should now work.
