### ISSUE TITLE
Waybar Pop-Ups Appear Behind Windows

### ISSUE THREAD

**Issue by BenEvolent333** [ifreund/river#89]
So, the popups for (for example) menus in the system tray appear behind any windows they should appear over. However, the focus remains on the popup, so I can still use them if the overlaid window is transparent, but it's not really usable if the window is opaque. I'm not sure if this is a waybar problem, or a river problem.

I am using waybar v0.9.3, and river from the latest git commit (340bfbd)

**Comment by ifreund** [comment]
Thanks for the bug report, I disable popups on waybar so I never would have noticed. This would be a river bug, it's an ordering issue with how popups are drawn.

**Comment by ifreund** [comment]
As a workaround you may want to add `"layer": "top"` to your waybar config until this is fixed.

**Comment by BenEvolent333** [comment]
Thank you, that ought to work for now!

**Comment by ifreund** [comment]
I'm inclined to put this on hold until the next wlroots release which will include #2398, making this much less annoying to implement.

**Comment by ifreund** [comment]
Fixed in 77d3eb1bf0555f9e7eafb2e83e90f6e6316056f3
