### ISSUE TITLE
The 'clickable area' is slightly off from any 'clickable thing' on the screen.

### ISSUE THREAD

**Issue by lazy-dolphin** [ifreund/river#9]
For example,  I can open a link in firefox even if I click on a position slightly above or slightly left from the link, but I cannot click on the bottom area or the right area of the link.
```
                   _______________
Clickable  area->  |   ___________|___
                   |___|__________|   | <- Where the button is
                       |______________|    shown on the screen

**Comment by ifreund** [comment]
I've noticed this too, will look into a fix.

**Comment by ifreund** [comment]
Should be fixed now!
