### ISSUE TITLE
[Feature request] Toggle add to top/add to bottom

### ISSUE THREAD

**Issue by BenEvolent333** [ifreund/river#90]
I think it would be useful to be able to toggle whether new windows are added to the top or the bottom of the stack. I made a layout which shows the top windows from the stack at the bottom, and puts the bottom windows in the master area, but this does have different functionality (i.e. swapping windows to the master now puts them at the bottom).

**Comment by ifreund** [comment]
This sounds like a reasonable feature to me, there are in fact a few more potentially useful behaviors for where to create new windows as well.

As #12 already includes this, I'm going do go ahead and close this as a duplicate.
