### ISSUE TITLE
[Bug] The Latest Git Commit Build Fails

### ISSUE THREAD

**Issue by BenEvolent333** [ifreund/river#94]
Building river with the command `zig build -Drelease-safe=true -Dxwayland=true`, both with and without `-Drelease-safe=true` and with and without `prefix --/usr install` doesn't build. The compiler message is

`zig build -Dxwayland=true --prefix /usr
error: AccessDenied
/usr/lib/zig/std/fs.zig:160:29: 0x2c0dcb in std.fs.AtomicFile.init (build)
                else => |e| return e,
                            ^
/usr/lib/zig/std/fs.zig:1351:13: 0x2bf69e in std.fs.Dir.atomicFile (build)
            return AtomicFile.init(path.basename(dest_path), options.mode, dir, true);
            ^
/usr/lib/zig/std/fs.zig:1305:27: 0x2b2899 in std.fs.Dir.updateFile (build)
        var atomic_file = try dest_dir.atomicFile(dest_path, .{ .mode = actual_mode });
                          ^
/usr/lib/zig/std/build.zig:851:29: 0x2b9cdb in std.build.Builder.updateFile (build)
        const prev_status = try fs.Dir.updateFile(cwd, source_path, cwd, dest_path, .{});
                            ^
/usr/lib/zig/std/build.zig:2234:9: 0x2b5259 in std.build.InstallArtifactStep.make (build)
        try builder.updateFile(self.artifact.getOutputPath(), full_dest_path);
        ^
/usr/lib/zig/std/build.zig:2394:9: 0x275afe in std.build.Step.make (build)
        try self.makeFn(self);
        ^
/usr/lib/zig/std/build.zig:404:9: 0x2744f3 in std.build.Builder.makeOneStep (build)
        try s.make();
        ^
/usr/lib/zig/std/build.zig:398:17: 0x27449a in std.build.Builder.makeOneStep (build)
                return err;
                ^
/usr/lib/zig/std/build.zig:359:13: 0x26a777 in std.build.Builder.make (build)
            try self.makeOneStep(s);
            ^
/usr/lib/zig/std/special/build_runner.zig:125:21: 0x26312d in main (build)
            else => return err,
                    ^
/usr/lib/zig/std/os.zig:3289:5: 0x283bde in std.os.realpath (build)
    return realpathZ(&pathname_c, out_buffer);
    ^
/usr/lib/zig/std/fs.zig:1665:36: 0x2834e2 in std.fs.realpathAlloc (build)
    return mem.dupe(allocator, u8, try os.realpath(pathname, &buf));
                                   ^
/usr/lib/zig/std/os.zig:885:23: 0x28fb22 in std.os.openZ (build)
            ENOENT => return error.FileNotFound,
                      ^
/usr/lib/zig/std/os.zig:3303:25: 0x283c89 in std.os.realpathZ (build)
            else => |e| return e,
                        ^
/usr/lib/zig/std/os.zig:3289:5: 0x283bde in std.os.realpath (build)
    return realpathZ(&pathname_c, out_buffer);
    ^
/usr/lib/zig/std/fs.zig:1665:36: 0x2834e2 in std.fs.realpathAlloc (build)
    return mem.dupe(allocator, u8, try os.realpath(pathname, &buf));
                                   ^
/usr/lib/zig/std/os.zig:885:23: 0x28fb22 in std.os.openZ (build)
            ENOENT => return error.FileNotFound,
                      ^
/usr/lib/zig/std/os.zig:3303:25: 0x283c89 in std.os.realpathZ (build)
            else => |e| return e,
                        ^
/usr/lib/zig/std/os.zig:3289:5: 0x283bde in std.os.realpath (build)
    return realpathZ(&pathname_c, out_buffer);
    ^
/usr/lib/zig/std/fs.zig:1665:36: 0x2834e2 in std.fs.realpathAlloc (build)
    return mem.dupe(allocator, u8, try os.realpath(pathname, &buf));
                                   ^
/usr/lib/zig/std/os.zig:885:23: 0x28fb22 in std.os.openZ (build)
            ENOENT => return error.FileNotFound,
                      ^
/usr/lib/zig/std/os.zig:3303:25: 0x283c89 in std.os.realpathZ (build)
            else => |e| return e,
                        ^
/usr/lib/zig/std/os.zig:3289:5: 0x283bde in std.os.realpath (build)
    return realpathZ(&pathname_c, out_buffer);
    ^
/usr/lib/zig/std/fs.zig:1665:36: 0x2834e2 in std.fs.realpathAlloc (build)
    return mem.dupe(allocator, u8, try os.realpath(pathname, &buf));
                                   ^
/usr/lib/zig/std/os.zig:1767:19: 0x274ccc in std.os.mkdiratZ (build)
        EEXIST => return error.PathAlreadyExists,
                  ^
/usr/lib/zig/std/os.zig:1750:9: 0x274b9b in std.os.mkdirat (build)
        return mkdiratZ(dir_fd, &sub_dir_path_c, mode);
        ^
/usr/lib/zig/std/fs.zig:744:9: 0x274a36 in std.fs.Dir.makeDir (build)
        try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
        ^
/usr/lib/zig/std/os.zig:1767:19: 0x274ccc in std.os.mkdiratZ (build)
        EEXIST => return error.PathAlreadyExists,
                  ^
/usr/lib/zig/std/os.zig:1750:9: 0x274b9b in std.os.mkdirat (build)
        return mkdiratZ(dir_fd, &sub_dir_path_c, mode);
        ^
/usr/lib/zig/std/fs.zig:744:9: 0x274a36 in std.fs.Dir.makeDir (build)
        try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
        ^
/usr/lib/zig/std/os.zig:921:23: 0x25e0c6 in std.os.openatZ (build)
            EACCES => return error.AccessDenied,
                      ^
/usr/lib/zig/std/fs.zig:699:13: 0x2bda16 in std.fs.Dir.createFileZ (build)
            try os.openatZ(self.fd, sub_path_c, os_flags, flags.mode);
            ^

Build failed. The following command failed:
/home/zachir/git/river/zig-cache/o/MdGRU8xh-XH8NmB4MHeSdx2nkh0cS_yG4NRe_i3g5XC4k4cAepSXZH5Gu2vux8-m/build /usr/bin/zig /home/zachir/git/river /home/zachir/git/river/zig-cache -Dxwayland=true --prefix /usr`

**Comment by Leon-Plickat** [comment]
Can't reproduce.

Are you sure you have a working installation of zig and the clang / LLVM stack?

Or maybe you have local changes. To get a clean master from upstream: `git fetch --all && git reset --hard origin/master`

**Comment by BenEvolent333** [comment]
It built perfectly fine with the last commit, nothing has changed in terms of zig/clang for me. I also just cloned the repo, and compiled without changing anything.

**Comment by Leon-Plickat** [comment]
Just took a look at the compiler message. `error: AccessDenied` is pretty indicative. zig probably wanted to access something outside your home directory and could not. Therefore I assume the error message you posted comes from when you used the `prefix` option without having the correct privileges.

You said zig also errors out without using `prefix`. Please provide a log of that.

**Comment by BenEvolent333** [comment]
Apparently that was the issue, although the first time I build it without the `--prefix /usr install` it failed, I can no longer reproduce the error after updating, so I am marking it as closed. It was probably just what you said, trying to install without root permissions.
