### ISSUE TITLE
Binaries? 

### ISSUE THREAD

**Issue by Scupake** [ifreund/river#96]
I've been trying to compile river for a while now, and I always keep failing, I would love it if somebody could provide some binaries.

**Comment by ifreund** [comment]
I don't intend to provide official binaries, distributing software is up to the various linux distributions (though I will package river for void linux myself after a first release).

If you'd like help getting river to build, feel free to stop by `#river` on freenode. Alternatively, you could give more details here such as the exact error you get, your distro, zig version, etc.
