### ISSUE TITLE
More advanced map 

### ISSUE THREAD

**Issue by maringuu** [ifreund/river#98]
I suggest implementing some mapping features from sway.

https://github.com/swaywm/sway/blob/afa890e8e9f10667a56e896a114bf81fbc3ff54a/sway/sway.5.scd#L384

`--no-repeat --locked --release` can be implemented right now I think. `--to-code --input-device` might require some more work.

I'll see how far I can get with this one tomorrow.

**Comment by ifreund** [comment]
I'd hesitate to implement features just because sway has them. We should make sure that new features have a real use-case if we want river to stay simple. Is there a specific use case you have that these new features would address.

**Comment by maringuu** [comment]
I have a use cases for `--no-repeat` and `--release`. It is rather gimmiky but still.

```
riverctl map normal $mod F toggle-fullscreen
riverctl map --release normal $mod F toggle-fullscreen
```
Often I see my self fullscreening a window for just several seconds. Also I sometimes want to have a quick look at the windows in the layout that are not currently show because there is a fullscreened window.
This could of course be archived with pressing `$mod F` twice but it would feel cooler if I could just hold it for a few seconds.
Also pausing music for some seconds would be cool.

One use case for `--locked` when I leave my laptop (locked) in a room with my friends. When they feel very funny they might exit river and thus close all my windows because the mapping got executed.

For the others I don't have a concrete usecase for my self.

**Comment by maringuu** [comment]
I just realised that commands are only executed once and not repeated.
A use case for repeating them would be turning up/down brightness or volume.

**Comment by ifreund** [comment]
> I just realised that commands are only executed once and not repeated.
A use case for repeating them would be turning up/down brightness or volume.
Maybe we should add (if desired) --repeat instead.

Agreed, I think a `--repeat` option would be preferable to a `--no-repeat`

> One use case for --locked when I leave my laptop (locked) in a room with my friends. When they feel very funny they might exit river and thus close all my windows because the mapping got executed.

I think we should disable all keybindings by default when input is inhibited (e.g. by a lockscreen). We could then consider adding a `--locked` option to bypass this restriction which might be desirable for e.g. music player controls (which is how sway's works as well iirc).

`--release` should be fairly trivial to implement and I can see it being useful so I wouldn't mind having that.

**Comment by ifreund** [comment]
Oh, and since these are the first options we are adding to a command, let's make sure we establish good conventions. I think I'd like to take a page out of kakoune's book and use only a single `-` to prefix flags as I don't think we should support "short" flags. This would give us for example:
```
riverctl map -repeat normal Mod4 H mod-master-factor -0.05
```

**Comment by maringuu** [comment]
> Oh, and since these are the first options we are adding to a command, let's make sure we establish good conventions. I think I'd like to take a page out of kakoune's book and use only a single `-` to prefix flags as I don't think we should support "short" flags. This would give us for example:
> 
> ```
> riverctl map -repeat normal Mod4 H mod-master-factor -0.05
> ```

Good idea!
I agree on never adding short options since they are too unreadable.

**Comment by Leon-Plickat** [comment]
> `-locked`

Or we could simply add a second default mode, "locked", to which river automatically switches when the screen is locked.

**Comment by ifreund** [comment]
> Or we could simply add a second default mode, "locked", to which river automatically switches when the screen is locked.

Let's do this, no need to add another flag!

**Comment by Leon-Plickat** [comment]
Does river already know when the screen is locked? I grepped through the code a bit yesterday but could not find anything.

We should also ensure that this mode can not be entered or exited by any other way then locking and unlocking the screen.

**Comment by ifreund** [comment]
> Does river already know when the screen is locked? I grepped through the code a bit yesterday but could not find anything.

This is handled through the `wlr-input-inhibit` protocol which we implement through `handleInhibitActivate` and `handleInhibitDeactivate` in `InputManager.zig`.

> We should also ensure that this mode can not be entered or exited by any other way then locking and unlocking the screen.

Agreed, a check in the handling of the `enter-mode` command should be sufficient.

**Comment by Leon-Plickat** [comment]
Is binding the "locked" mode to the wlr-input-inhibit really the right way to do this? AFAIK there are other thing triggering the inhibitor, like remote desktop viewers. And sway has both `--locked` and `--inhibit`  keybind modifiers, so they probably use something else.

**Comment by ifreund** [comment]
implementation of `-repeat` is tracked by #306. `-release` is already implemented as is the `locked` mode described above. For the rest, I'd like to see a new issue with motivating use-case before implementation.
